### ISSUE TITLE
Failures during makefile. 

### ISSUE THREAD

**Issue by deepio** [ruven/iipsrv#119]
I'm not sure if this particular issue is in the correct location. While running make, I get the error: 

> Makefile:438: recipe for target 'iipsrv.fcgi' failed
> make[1]: *** [iipsrv.fcgi] Error 1
> make[1]: Leaving directory '/usr/bin/Rodan/iipsrv/src
> Makefile:408: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

I'm using kakadu 7.6, and there are many undefined references to these files:

> jp2.h
> jpx.h
> kdu_elementary.h
> kdu_ubiquitous.h
> kdu_compressed.h
> kdu_threads.h
> kdu_arch.h
> kdu_params.h
> kdu_messaging.h
> kdu_kernels.h
> kdu_sample_processing.h
> kdu_cache.h
> kdu_client_window.h
> kdu_stripe_decompressor.h

Not sure if this is a kakadu issue or an iipsrv one.

**Comment by ahankinson** [comment]
You will have to provide a bit more information. Could you show the `make` command you are running?

**Comment by deepio** [comment]
I solved the issue a while ago. I created a vm using ubuntu (16.04 LTS), installed and moved the files manually.  
Once the files where moved, I just needed to do this. 

sudo apt-get install libtool (if you didn't already have it ) 
./autogen.sh
./configure --with-kakadu=/kakadu/bin
make
