### ISSUE TITLE
Stable branch

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [ruven/iipsrv#120]
Hi, 

We use IIPsrv for many of our projects and it is now part of our regular builds using docker. We usually get the latest version as it will contains bug fixes but I'm wondering how stable it is? Is the master branch more stable than develop? Do you use any test suite to avoid regression?

Thanks for the software,

Best

**Comment by ruven** [comment]
Yes, the master branch can be considered reasonably stable, while the development branch will contain more experimental code. If you want a fully tested and stable version, you should stick with the last release (version 1.0) unless there is some specific new feature you are looking for.

There isn't a proper test suite at the moment, but it would certainly be a good idea to do one.
