### ISSUE TITLE
iipsrv does not fail gracefully on some malformed JP2 images

### ISSUE THREAD

**Issue by jothomp-dev** [ruven/iipsrv#123]
Here is an example of a malformed JP2 image that will cause iipsrv to crash:
https://cdn.loc.gov/service/sgp/sgpbatches/batch_dlc_germanrex_ver01/data/sn83025887/print/1793022001/0001.jp2

Here is the message printed to the iipsrv log.  Note how there is nothing printed after "JPEG2000 image detected" -- the server dies silently:
> Full Request is IIIF=/service/sgp/sgpbatches/batch_dlc_germanrex_ver01/data/sn83025887/print/1791111401/0001.jp2/full/pct:6.25/0/default.jpg
> [1/1]: Command / Argument is IIIF : /service/sgp/sgpbatches/batch_dlc_germanrex_ver01/data/sn83025887/print/1791111401/0001.jp2/full/pct:6.25/0/default.jpg
> IIIF handler reached
> IIIF :: URL decoded to /service/sgp/sgpbatches/batch_dlc_germanrex_ver01/data/sn83025887/print/1791111401/0001.jp2/full/pct:6.25/0/default.jpg
> FIF handler reached
> FIF :: URL decoding/filtering: /service/sgp/sgpbatches/batch_dlc_germanrex_ver01/data/sn83025887/print/1791111401/0001.jp2 => /service/sgp/sgpbatches/batch_dlc_germanrex_ver01/data/sn83025887/print/1791111401/0001.jp2
> FIF :: Image cache initialization
> FIF :: JPEG2000 image detected

Apache responds with a 500 error.  Here is the message printed to the Apache error log:
> terminate called after throwing an instance of 'int'
> [Fri Jun 09 17:23:24.687592 2017] [fcgid:warn] [pid 28024:tid 139765324556032] [client 140.147.177.95:61872] mod_fcgid: error reading data, FastCGI server closed connection
> [Fri Jun 09 17:23:24.687652 2017] [core:error] [pid 28024:tid 139765324556032] [client 140.147.177.95:61872] End of script output before headers: iipsrv.fcgi
> [Fri Jun 09 17:23:25.476464 2017] [fcgid:error] [pid 28022:tid 139765415192448] mod_fcgid: process /home/john/iipsrv/iipsrv.fcgi(31023) exit(communication error), get signal 6, possible coredump generated

This is how Kakadu responds when running kdu_expand on this file:
> Error in Kakadu File Format Support:
> Incomplete set of colour channel definitions found in a `jp2_channels' object.
> This is likely due to a malformed channel definitions (cdef) box in the
> JP2-family data source.

Can iipsrv be modified to handle this error gracefully?

**Comment by ruven** [comment]
Your image in fact works fine for me. Which version of iipsrv and of Kakadu are you using?

**Comment by jothomp-dev** [comment]
I am using version 6.4.1.  It sounds like I need to upgrade.

**Comment by ruven** [comment]
OK, I just tried with 6.4.1 and the kdu utilities such as kdu_expand also fail with the same error, so the error is definitely coming from there. I'll try to add checks to in the iipsrv code to avoid this crash even with old Kakadu versions.

**Comment by ruven** [comment]
I just added a fix to avoid crashes in older versions of Kakadu.

**Comment by acdha** [comment]
Awesome, thanks!
