### ISSUE TITLE
existing file not found before restart

### ISSUE THREAD

**Issue by nicolasfranck** [ruven/iipsrv#127]
I have a strange issue, using the IIIF handler.

The storage is mounted, and the iipsrv uses the parameter FILESYSTEM_PREFIX ( /mnt/files/ ).
When the hosting server is restarted, an I test the IIIF handler, using an existing file, I get:

```
path/to/file.jp2 is neither a file nor part of an image sequence
```

But /mnt/files/path/to/file.jp2 actually exists!

I've set the loglevel to 6, but only this message is shown:

```
FIF :: Image cache initialization
```

The strace command shows this:

```
accept(0,

{sa_family=AF_INET, sin_port=htons(55971), sin_addr=inet_addr("10.0.2.2")}, [16]) = 4
setsockopt(4, SOL_TCP, TCP_NODELAY, [1], 4) = 0
read(4, "\1\1\0\1\0\10\0\0\0\1\0\0\0\0\0\0\1\4\0\1\2\320\0\0\f\37QUERY_"..., 8192) = 760
write(3, "FIF :: Image cache initializatio"..., 34) = 34
stat("path/to/file.jp2", 0x7fff5b5bab90) = -1 ENOENT (No such file or directory)
open("path/to", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(4, "\1\6\0\1\0m\3\0Status: 404 Not Found\r\nS"..., 120) = 120
write(4, "\1\6\0\1\0\0\0\0\1\3\0\1\0\10\0\0\0\0\0\0\0\0\0\0", 24) = 24
shutdown(4, 1 /* send */)               = 0
poll([{fd=4, events=POLLIN}], 1, 2000)  = 1 ([{fd=4, revents=POLLIN|POLLHUP}])
read(4, "", 1024)                       = 0
close(4)                                = 0
accept(0,
```

When restarting the iipsrv, it works again.
But it always happens after initial startup of the hosting server,
and sometimes during the lifetime of the iipsrv instance.

Any idea what can cause this? Is the filesystem_prefix directory opened in memory,
and kept in memory (could explain filesystem changes not being picked up, especially when
the directory is mounted some seconds after the startup of iipsrv)?

The storage is a mounted CIFS storage, but I've also seen this on locally mounted storage.

Not sure whether this is related to the IIIF handler, or more broadly.

**Comment by ruven** [comment]
> Is the filesystem_prefix directory opened in memory

No, the file is only accessed when needed - no directories or file systems are put into memory.

> stat("path/to/file.jp2", 0x7fff5b5bab90) = -1 ENOENT (No such file or directory)

It's the POSIX stat() function which is not finding the file. Is this only occurring if iipsrv is the first application to access the file system? What happens on a second iipsrv request to the same file? 

It looks to me like a file mounting issue rather than iipsrv-specific, but you can test this by writing a few lines code in C to open the file with stat() (there's an example in the stat man page) and check whether this still happens.

**Comment by nicolasfranck** [comment]
My bad, this was actually caused by the environment configuration not being included during
boot. So the FILESYSTEM_PREFIX was empty..

I have two init scripts:
* iipsrv
* iipsrv_ugent

They contain the same code, but both need a different sysconfig code to load the environment.
So I needed to get the "basename" of the init-script to figure out the path of the sysconfig:
```
base=$(basename $0)
syconfig=/etc/sysconfig/${base}.conf
```

Which resolves to "/etc/sysconfig/S85iipsrv.conf" during  boot, which is of course never found..
