### ISSUE TITLE
Intermittent hangs -- help debugging

### ISSUE THREAD

**Issue by ahankinson** [ruven/iipsrv#131]
I've been seeing intermittent hangs of IIP -- sometimes its down to every few hours; other times it will go for a week or more. I'm working on the assumption that there are some images that we're serving that are not properly encoded, and a user accessing those images triggers the hang. When it hangs, IIP starts using all available CPU and becomes non-responsive.

Unfortunately I'm having problems tracking down which images are causing this. In the IIP error logs, grepping for the word "Error" gives me entries like this:

```
IIIF :: Requested Rotation: 0 degrees
IIIF :: Requested Quality: default with format: jpg
IIIF :: image request for /GB-Ob_Mus.e.3_Sadler/GB-Ob_Mus.e.3_039r.jpx with arguments: region: 0,4096,4096,2288; size: 256x143; rotation: 0; mirroring: 0
CVT handler reached
CVT :: Using resolution 2 with size 560x399
CVT :: Region: 0,256,256,143
CVT :: Requested scaled region size is 256x143 at resolution 2. Nearest existing resolution has region with size 256x143
TileManager getRegion :: requesting region directly from image
CVT :: Error flushing jpeg data
CVT :: About to JPEG compress strip with height 128
CVT :: Compressed data strip length is 9824
CVT :: Error writing jpeg strip data: 9824
CVT :: About to JPEG compress strip with height 15
CVT :: Compressed data strip length is 508
CVT :: Error writing jpeg strip data: 508
CVT :: Error writing jpeg EOI markers
CVT :: Total command time 198026 microseconds
IIIF :: Total command time 198557 microseconds
Memcached :: stored 10568 bytes in 56 microseconds
Total Request Time: 205579 microseconds
image closed and deleted
Server count is 1117
```

When I try accessing this image directly, though, it works fine.

I'm running IIP in a round-robin FastCGI setup through NginX with four instances of IIP. I'm going to be investigating the NginX/FastCGI part of it (possibly it's hanging there?) but thought I would see if the error messages about flushing the data would be in any way related to the behaviour I'm seeing.

Thanks!

**Comment by ruven** [comment]
The errors are all related to writing the data to output through the FCGI interface. It doesn't seem to be related to any image encoding problems. Maybe there's some FCGI output buffer issue? There are ways to control [the buffer size in NginX](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_buffer_size). Try increasing, for example, _fastcgi_buffer_size_  to see if this helps.

Maybe iipsrv should handle this kind of error better rather than just ignoring it as now. I'll take a look into it.

**Comment by ahankinson** [comment]
I haven't had any hangs lately, so I'm going to close this as fixed now.
