### ISSUE TITLE
Cache invalidation based on mtime of file

### ISSUE THREAD

**Issue by nicolasfranck** [ruven/iipsrv#135]
I wondered how the cache invalidation works in the iipsrv.
When does the server decide when to invalidate a tile from the cache?
Based on the LRU algorithm alone?

It would be handy if the entries could be invalidated when the time last modified (mtime)
of the file changes. This could be done easily by adding the mtime to the key of the cache entry.
Older entries would then be invalidated automatically because no one requests them anymore.

I often had the case that the cache still delivers old tiles when the file has changed, leading to confusion in the viewer.

**Comment by ruven** [comment]
Are you talking about the internal iipsrv cache or Memcached? If you take a look in FIF.cc you'll see that there is indeed a check for file modification time, so you should always get new tiles if the file has changed on disk. However, for Memcached, this timestamping mechanism is currently bypassed.

**Comment by nicolasfranck** [comment]
Mm, maybe it was just the cache of the frontend server. Sorry for bothering ;-)
