### ISSUE TITLE
Compiling on Windows without Kadaku

### ISSUE THREAD

**Issue by dennisai** [ruven/iipsrv#141]
I don't have any need for JPEG2000 support in my application, and would like to try out IIPServer on Windows.  I have been following this [guide](http://help.oldmapsonline.org/jpeg2000/windows/how-to-build-windows-binaries), and removed the pre-processor definitions in Visual Studio.

"If you don't want to build with Memcached or Kakadu remove appropriate preprocessor definition
    Project properties -> C/C++ -> Preprocessor -> Preprocessor Definitions: HAVE_KAKADU;HAVE_MEMCACHED; 

However, after doing that, I still get the following errors related to not having "jp2.h" or "jpx.h".  Is it necessary to have Kadaku SDK for compiling from source?
![image](https://user-images.githubusercontent.com/1017972/34071352-49724478-e243-11e7-87a8-fe2cedca323a.png)

**Comment by stweil** [comment]
That guide is rather old and does not match the current code. It is possible to build iipsrv with [OpenJPEG](https://github.com/uclouvain/openjpeg/) instead of Kakadu. I never tried that with Visual Studio, so I am sorry that I cannot help more.

**Comment by ahankinson** [comment]
It's also possible to build without either, without touching the code.

**Comment by ruven** [comment]
Correct. Neither Kakadu or OpenJPEG are dependencies and can be removed from the Visual Studio config.
