### ISSUE TITLE
Error C3861: 'snprintf': identifier not found (compiling in VSE2010)

### ISSUE THREAD

**Issue by tmtisfree** [ruven/iipsrv#142]
According to [1], 'snprintf' which is found in 'JPEGCompressor.cc' is not available in VisualStudio 2010 Express (VSE2010), and that results in an error when compiling.

A workaround (also from [1]) is to do the following to the 'JPEGCompressor.cc' file:

between:
`using namespace std;`
and:
`#define MX 65535`

add the following:
```
#if defined(_MSC_VER) && _MSC_VER < 1900
#include <iostream>
#include <cstdarg>
#define snprintf c99_snprintf
#define vsnprintf c99_vsnprintf

__inline int c99_vsnprintf(char *outBuf, size_t size, const char *format, va_list ap)
{
    int count = -1;

    if (size != 0)
        count = _vsnprintf_s(outBuf, size, _TRUNCATE, format, ap);
    if (count == -1)
        count = _vscprintf(format, ap);

    return count;
}

__inline int c99_snprintf(char *outBuf, size_t size, const char *format, ...)
{
    int count;
    va_list ap;

    va_start(ap, format);
    count = c99_vsnprintf(outBuf, size, format, ap);
    va_end(ap);

    return count;
}
#endif

```

[1] https://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010

**Comment by ruven** [comment]
There's an easier way to do this by just adding the line for Windows:

`#define snprintf _snprintf`

This is already used elsewhere in the code and works fine. I just made a commit that adds this to JPEGCompressor.h

**Comment by tmtisfree** [comment]
I am no coder ;)
