### ISSUE TITLE
IIIF :: Only JPEG output supported

### ISSUE THREAD

**Issue by stephanpauls** [ruven/iipsrv#145]
Hi 

When i try to open a manifest file in universal viewer, the thumbnails are not opened.
The error that i got is: 'IIIF :: Only JPEG output supported' 

The url is https://services.libis.be/iipsrv/iipsrv.fcgi?iiif=/operational_storage/storage1/2017/12/07/file_56/V1-FL10046119.jp2/full/90,/0/default.jpg?t=1520258543365

If the t=1520258543365 is removed the url shows a thumbnail though.

Stephan pauls

**Comment by ruven** [comment]
The t=n is being parsed as a literal part of the final IIIF parameter. The easiest way to get around this is to use your web server's rewrite feature to strip this out before the URI is passed to iipsrv

**Comment by macarthy** [comment]
Is this still valid ? or is there a better solution now?

**Comment by ruven** [comment]
I've now added code to strip any suffixes of the form ?=xxx, which should fix this kind of problem: https://github.com/ruven/iipsrv/commit/d4a701864877cb22ec6212c284ccd733ce3106d8
