### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by bubba-h57** [ruven/iipsrv#146]
I am looking for a simple solution to monitoring and reporting (Grafana) on IIP. Are there any good solutions already in place?

**Comment by ruven** [comment]
There's no integrated support for any monitoring software, but as requests transit through a standard web server first, which will be able to hook into any monitoring environment, you could configure the monitor to only use, for example, the /fcgi-bin/iipsrv.fcgi location.

What level of detail are you looking for in your monitoring? Maybe we could put together a simple plugin for Grafana or similar?

**Comment by bubba-h57** [comment]
A lot of the interesting data is found in the log file if you crank it up high enough. 

We would like to graph:
- Requests Handled in the past N seconds 
- Cache Hits in the past N seconds
- Avg/median Total Request Times in the past N seconds
- Max MEM used in the past N seconds
- Max CPU used in the past N seconds

Parsing the log files for the data is not impossible, but it is not elegant. We use [InfluxDB](https://www.influxdata.com/time-series-platform/influxdb/) ourselves for collecting/querying time series data and Grafana for building our dashboards.

Perhaps one of the simplest paths forward would be an option to log each event (request) in a machine consumable format like json? For my purposes, I would then have Telegraf consume and parse the logs, logging each event in InfluxDB. I believe others should be able to use their client of choice to parse/manage the logs as well?

**Comment by ruven** [comment]
The iipsrv log file doesn't currently include timestamps, so even with parsing, these kind of time-based stats are not readily available via the current log file. Also any iipsrv logging won't be able to give you memory or CPU usage, so you'll need to get these through an external probe.

It would be definitely be good, however, to switch iipsrv to a better system of logging, not based on simply writing out to a file. What about using something standard like syslog? Or through a library such as [log4c](http://log4c.sourceforge.net/)? Any thoughts?

**Comment by bubba-h57** [comment]
Something like log4c would be fantastic ... the admin can then setup whichever and however many appenders they like.

**Comment by ruven** [comment]
I just added a generic Logger class (https://github.com/ruven/iipsrv/commit/f68b225013c54dd08badcd55d0819d29eb4fc5f8), which supports output to a file and additionally supports logging via syslog. InfluxDB supports [syslog input](https://docs.influxdata.com/telegraf/v1.10/plugins/inputs/#syslog) and the new architecture makes it very easy to add support for log4c or other logging libraries.
