### ISSUE TITLE
EXIF orientation tag ignored

### ISSUE THREAD

**Issue by mel-mason** [ruven/iipsrv#147]
I've got a TIFF with `Orientation: Rotate 270 CW` in its EXIF metadata, which means it's automatically rotated when I view it in most software. When I convert it to JPEG2000 (using Kakadu), that Orientation value is retained in the metadata. But when I then serve that JP2 using IIIF parameters (full/full/0/default.jpg) via iipsrv, the jpg I'm returned is not rotated according to the orientation tag, and doesn't have the tag in its metadata.

This may well be expected behaviour for iipsrv, but I wanted to flag it up just in case.

I'm using IIPImage built from the most recent commit eb8602ae40ff03aadf6abdc9fb8ef0f54c71c577.

Thanks

**Comment by ruven** [comment]
> This may well be expected behaviour for iipsrv, but I wanted to flag it up just in case.

You're right. iipsrv does not handle orientation tags. To get around this, you can ask Kakadu to rotate the image during encoding through the -rotate flag. You need to supply the rotation angle, however, so in this particular case, you would need to specify -rotate 270.

**Comment by mel-mason** [comment]
OK, thanks for the quick response :)
