### ISSUE TITLE
Jpeg2000 jpf files crashing iip image server

### ISSUE THREAD

**Issue by faheemziker** [ruven/iipsrv#152]
on serving jpf files iip image server crash.
file link
https://www.dropbox.com/s/yacsqbwjsrhlb21/n2017050015.jpf?dl=0

also one more question which is not specifically related to iip image server but ill be very thankful to you if you give some help/suggestion.

when i try to expand the same file using kakadu tools 
it gives me 

```
> Error in Kakadu File Format Support:
> The `curv' data type used to represent an embedded ICC profile's tone
> reproduction curve appears to have been truncated.
```
can you help me to find out whats the issue and how i can fix this issue.

**Comment by ruven** [comment]
This shouldn't crash any recent development versions of the IIPImage server. The server should report the error and continue. What version are you running? 

I don't know exactly what's wrong with your file and why Kakadu cannot decode this - the error message is not very clear. But OpenJPEG is in fact able to decode this image properly, so you can use this to decode then re-encode the file correctly.

**Comment by faheemziker** [comment]
HI Ruven,
Thanks for your quick and detailed response.
I am using
IIPImage Server. Version 1.0

here are the logs when i try to server jpf file its just stopped without any error message  and as i have setup monit so its automatically restarted

here are the full logs

`

Full Request is IIIF=DIR_PATH/c61bf2fa-7f30-4b95-94dc-ae41e484cf05.jpf/info.json
[1/1]: Command / Argument is IIIF : DIR_PATH/c61bf2fa-7f30-4b95-94dc-ae41e484cf05.jpf/info.json
IIIF handler reached
IIIF :: URL decoded to DIR_PATH/c61bf2fa-7f30-4b95-94dc-ae41e484cf05.jpf/info.json
FIF handler reached
FIF :: URL decoding/filtering: DIR_PATH/c61bf2fa-7f30-4b95-94dc-ae41e484cf05.jpf => DIR_PATH/c61bf2fa-7f30-4b95-94dc-ae41e484cf05.jpf
FIF :: Image cache miss
FIF :: JPEG2000 image detected


[2018-05-08 05:06:18] - INFO - Starting IIP Image Server...
<----------------------------------->
Tue May  8 05:06:18 2018

IIPImage Server. Version 1.0
*** Ruven Pillay <ruven@users.sourceforge.net> ***

Verbosity level set to 6
Running in FCGI mode

Setting maximum image cache size to 10MB
Setting default JPEG quality to 75
Setting maximum CVT size to 5000
Setting HTTP Cache-Control header to 'max-age=86400'
Setting 3D file sequence name pattern to '_pyr_'
Setting Cross Origin Resource Sharing to '*'
Setting up JPEG2000 support via Kakadu SDK


Initialisation Complete.
<----------------------------------->

[2018-05-08 05:06:28] - INFO - Started IIP Image Server...

`

**Comment by ruven** [comment]
Upgrade to the latest development version of iipsrv on Github and this will fix the crashing issue.

**Comment by faheemziker** [comment]
Thanks for the help
i will upgrade it
