### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by stweil** [ruven/iipsrv#153]
There have been significant changes since the [last tagged release](https://github.com/ruven/iipsrv/releases/latest), so having a new release with those improvements and new features like support for OpenJPEG would be appreciated.

**Comment by ahankinson** [comment]
+1 for this. It would be handy to have a 'stable' version to pin.

**Comment by geoffroy-noel-ddh** [comment]
+1 having tags in github for each minor version would be useful.

**Comment by stweil** [comment]
The new release 1.1 is now available, thank you @ruven.

**Comment by ruven** [comment]
Sorry it took so long! And thanks @stweil for your numerous contributions to this release!
