### ISSUE TITLE
Cached info.json response does not accommodate http/https

### ISSUE THREAD

**Issue by ahankinson** [ruven/iipsrv#154]
The key for a memcached info.json response is based on the query parameters, but the `@id` value for this response does not take into account a dynamically requested protocol. So if two clients ask for the same image, but one over HTTP and one over HTTPS, the `@id` value in the `info.json` response will contain an incorrect value.

To fix this either:

a) add a parameter in the memcached key that incorporates the request protocol and store two versions of the response in memcached under different keys; or
b) rewrite the cached response to reflect the requested protocol. 

I believe a) would be the more appropriate solution, and that storing the full request URI as the key, instead of just the query parameter, might be a better choice.

**Comment by ruven** [comment]
I'm not too keen on the idea of adding HTTP protocol information to the memcached index key. Are there any real problems created by having an info.json `@id` with a different protocol to the actual request? Also don't forget that if someone is using the BASE_URL setting both the protocol and domain will be hard-wired in the  `@id` response.

I'm not sure what the best solution is here. I guess you could also add option (c) which would be not to cache info.json responses.

**Comment by ahankinson** [comment]
If you are serving info.json files over both HTTP and HTTPS, your info.json `@id` will reflect the cached version (i.e., the version that was requested first) rather than the one that matches the current protocol for the requested info request.  

It also breaks our testing frameworks. If we are running tests against an internal IIP server that is also serving staging content, we will get an `@id` value of something like "http://localhost:30000/iiif/image/blahblah/info.json`, which is the version requested from the testing environment (since it was first), rather than from the staging environment.

With `BASE_URL` it only rewrites the base, not the full URL, for the @id. So if we have incoming:

https://iiif.bodleian.ox.ac.uk/iiif/image/abc123/info.json

and we translate this to:

http://digital1-prd-images.bodleian.ox.ac.uk/fcgi/iipsrv.fcgi?IIIF=/abc123/info.json

Then using BASE_URL of `https://iiif.bodleian.ox.ac.uk/iiif/image` would give the (incorrect):

https://iiif.bodleian.ox.ac.uk/iiif/image?IIIF=/abc123/info.json

That's why the `HTTP_X_IIIF_ID` is in there -- to explicitly override the full ID instead of just the BASE_URL. This works well -- except that this value gets cached in the `info.json`, so it can give a wrong result if the requested version is different than the cached version.

**Comment by ahankinson** [comment]
Since info.json responses are no longer cached, this can be closed.
