### ISSUE TITLE
unrecognized signature of tiff image

### ISSUE THREAD

**Issue by sbarex** [ruven/iipsrv#155]
I have some tiff images that iipsrv don't recognize (unsupported format).
The code check the signature file (`IIPImage::testImageType()`).
My tiff has this signature: 0x4D 0x4D 0x00 0x2A.
The signature database https://www.garykessler.net/library/file_sigs.html identify this code as a Tagged Image File Format file (big endian, i.e., LSB last in the byte; Motorola).

**Comment by ruven** [comment]
OK thanks. I've committed a fix to this. Please try again with the latest source code from git.
