### ISSUE TITLE
MAX_CVT output size should be provided in the info.json

### ISSUE THREAD

**Issue by christopher-johnson** [ruven/iipsrv#157]
When MAX_CVT is applied to an image, the dimensions of the image provided by the info.json are not updated.   The client expects the image dimensions provided in the info.json to correspond to the full dimensions of max size request.  This dimension mismatch between the info.json and the serialized file results in a client's inability to correspond calculated image geometry (e.g. for annotations) from the info.json with the actual tiledImage.

**Comment by christopher-johnson** [comment]
this issue could be handled with the addition of one of `maxWidth`, `maxHeight` or `maxArea` to the info.json.  These properties are part of the the [Image API 2.1.x spec.](https://iiif.io/api/image/2.1/#profile-description)

**Comment by christopher-johnson** [comment]
See  https://github.com/ruven/iipsrv/issues/157 for discussion

**Comment by ruven** [comment]
I just added maxWidth and maxHeight to info.json through this commit: d5534ede41d585e97e4b86772567df00e39ac4f3
