### ISSUE TITLE
Image glitch on image edge at certain zoom levels

### ISSUE THREAD

**Issue by kevinc-cogapp** [ruven/iipsrv#158]
Hi,
We are having an issue with some of our images wherein they are displaying 'jagged' edges at some zoom levels. We think this may be a sub-pixel rounding issue and have been able to reproduce as follows:

- Create an image with dimensions 12868x9400 (In the test case a solid blue rectangle)
- Convert the image to a ptif with tile-geometry=128x128
- View the following image tiles (with results):

/iiif/test_image.ptif/4096,8192,4096,1208/128,/0/default.jpg
![image](https://user-images.githubusercontent.com/35451868/49506876-24620380-f877-11e8-93ff-932b29c0da87.png)

/iiif/test_image.ptif/0,8192,8192,1208/128,/0/default.jpg
![image](https://user-images.githubusercontent.com/35451868/49506921-3e9be180-f877-11e8-83da-c026c468e4a8.png)

/iiif/test_image.ptif/8192,8192,4096,1208/128,/0/default.jpg
![image](https://user-images.githubusercontent.com/35451868/49506948-4f4c5780-f877-11e8-8216-a094d63b1383.png)

/iiif/test_image.ptif/0,8192,4096,1208/64,/0/default.jpg
![image](https://user-images.githubusercontent.com/35451868/49507077-9c302e00-f877-11e8-91e1-710dbffb126c.png)

Having a size component that is 128 or 64 causes this issue - we haven't been able to reproduce with any other.

We've tried changing the iipsrv settings, how the image is converted and limiting upscaling. 

Is this a configuration issue our end or an underlying issue with the sub-pixel rounding as we expect?

Cheer.

**Comment by arnocertic** [comment]
:+1: 
We've got the same problem on the bottom of our images.
- Full image is ~ 480000x5500px
- We make the tiled version with vips and a size of 256x256 for each tile
- Leaflet is used to render tiled image and the bottom images present at some zoom scale the same problem you mention.
- The IIIF url is well formed : ....image.tif/67584,4096,2048,1454/256,/0/default.jpg
So the width is well set but the height of image is calculated by IIPServer and returns a additional non-wanted line.

I made a little hack on leaflet js library to force the height calcul (with a floor operation), and it works !

See issue #148

**Comment by ruven** [comment]
OK, I've added a fix for this, which also fixes issue #148 in this commit https://github.com/ruven/iipsrv/commit/cabd72aeca6f1cefae7c75c383f541fd7d2cb2cf

There was indeed a rounding issue. iipsrv now rounds to the nearest pixel number with round() rather than using floor() or ceil(). It's also depends on how the underlying image has been created and whether the existing resolutions layers have been created rounded up or down.

This works for all your examples, but please test and let me know if you find any other problems.

**Comment by kevinc-cogapp** [comment]
Great - thanks @ruven! 

We'll test this on our images and feedback if there are any more issues.
