### ISSUE TITLE
Some RGN requests failing.

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [ruven/iipsrv#16]
I have a weird situation where RGN requests with some particular range of values on the same JP2 image will fail. I have notice this bug a while ago, just tested it today again with the latest version of iipsrv (obtained from GIT yesterday) and Kakadu 7.3.3.

The same requests will work well with iipsrv 0.9 though.

If you are interested I can send the image (25MB) and the request over to you to help you reproducing the error.

**Comment by geoffroy-noel-ddh** [comment]
Hi, sorry I left this unanswered as I've used a work around since I discovered this bug.
Now we have a few projects based on IIPSrv and this issues is causing more trouble so please let me know if I can help you reproducing it.

I've just rebuilt the latets version of iipsrv today with kakadu 7.4.0 and the I can systematically reproduce the issue described above with that particular JP2 image. It also occurs with other images but the regions causing an error varies.

How can I send you the image file? It is pretty big and it is copyrighted so I can't give a public link to it.

Thanks in advance for your help.

Geoffroy

**Comment by ruven** [comment]
OK, if you send a link to it to ruven@users.sourceforge.net, I'll try to figure out what's going wrong

**Comment by ruven** [comment]
OK, I think I've found the problem. I've just uploaded a fix - please try it out and tell me if it works for all your problem images.

**Comment by geoffroy-noel-ddh** [comment]
Working well now, thank you very much for the prompt resolution!
