### ISSUE TITLE
Unhandled errors from TIFFReadDirectory result in corrupt images and metadata

### ISSUE THREAD

**Issue by oceanful** [ruven/iipsrv#168]
The return value of 0 from `TIFFReadDirectory()` does not distinguish between the case in which there are no more directories and the case in which an error occurred (the latter of which is surfaced via a separate `TIFFError()` channel).

Currently, the `TPTImage::loadImageInfo()` assumes the former, which can result in corrupt images and metadata, for instance when there's an underlying I/O problem. 

This is an example of what it looks like, when using `TIFFSetErrorHandler()` to output TIFFError messages to the session log file:

```
Full Request is DeepZoom=foo.tif_files/8/0_0.jpg
[1/1]: Command / Argument is DeepZoom : foo.tif_files/8/0_0.jpg
DeepZoom handler reached
FIF handler reached
FIF :: URL decoding/filtering: foo.tif => foo.tif
FIF :: Image cache initialization
FIF :: TIFF image detected

////// Errors that happen during TIFFReadDirectory()
TIFF Error :: /tmp/images/foo.tif: Can not read TIFF directory count
TIFF Error :: Failed to read directory at offset 1404962700

FIF :: Created image
FIF :: Image dimensions are 97792 x 219648
FIF :: Image contains 3 channels with 8 bits per channel
FIF :: Image timestamp: Mon, 22 Apr 2019 23:47:20 GMT
FIF :: Total command time 5991236 microseconds

////// This is wrong: there should actually be 11 numResolutions
DeepZoom :: required resolutions : 18, real: 10

DeepZoom :: Tile request for resolution: 0 at x: 0, y: 0
JTL handler reached
TileManager :: Cache Miss for resolution: 0, tile: 0
TileManager :: Cache Size: 0 tiles, 0 MB
TileManager :: Cropping tile
TileManager :: Edge tile: Base size: 256x256: This tile: 191x256
TileManager :: JPEG Compression Time: 359 microseconds
TileManager :: Tile cache insertion time: 16 microseconds
TileManager :: Total Tile Access Time: 907 microseconds
JTL :: Tile size: 191 x 256
JTL :: Channels per sample: 3
JTL :: Bits per channel: 8
JTL :: Data size is 4626 bytes
JTL :: Total command time 1038 microseconds
DeepZoom :: Total command time 5992374 microseconds
Memcached :: stored 4796 bytes in 333 microseconds
Total Request Time: 5993843 microseconds
image closed and deleted
Server count is 1
```

with the corruption being that loadImageInfo() only read 10 resolutions, while the image actually has 11. This results in serving the wrong tile and caching the corrupted metadata.

Detecting this would requiring using `TIFFSetErrorHandler` to surface these out-of-band errors; I don't have a great suggestion on how to do this cleanly.  :(

But for what it's worth, it would be nice if such errors resulted behavior similar to throwing a `file_error`, as opposed to returning a corrupted 200 response.

**Comment by ruven** [comment]
What about simply adding an error handler that throws an exception? Something like this:

```
// Handler to throw exception in case of TIFF error
static void errorHandler( const char* module, const char* fmt, va_list args ){
  char buffer[1024];
  snprintf( buffer, sizeof(buffer), fmt, args );
  throw file_error( "TPTImage :: TIFF error: " + string(buffer) );
}
```
Then just setting this with

`  TIFFSetErrorHandler( errorHandler );`

**Comment by oceanful** [comment]
That sounds simple and straightforward!

Would you set it globally in `Main.cc` or set/unset it at entry/exit points in TPTImage? I wasn't sure if it would be safe to throw a file_error from anywhere (here's where my ignorance shows), but if it is safe it certainly simplifies things.

A tangential but related request would be to log TIFFWarnings to the session log with the analogous TIFFSetWarningHandler method. That seems safe to do once globally (e.g. in `Main.cc`).

(btw, vsnprintf is a handy version of snprintf that directly handles the va_list)

Thanks for looking into this!

**Comment by ruven** [comment]
Thanks for having flagged this up. This is finally resolved with this commit: https://github.com/ruven/iipsrv/commit/41d44cbd46da39ab8e9617d52d76fc02d3d813de
