### ISSUE TITLE
Problem with JPEG2000 images in IIPImage with OpenJPEG support

### ISSUE THREAD

**Issue by regisrob** [ruven/iipsrv#172]
Hello Ruven,

I'm facing an issue with some JPEG2000 images in the last version  of IIPImage (last commit 6d42d47). 
IIP has been compiled successfully with OpenJPEG 2.3.1. Note that I have other instances of IIP like this that work perfectly fine...

I have a few JP2 images that have been created with Kakadu using the following profile:

~~~
kdu_compress -i input.TIF -o output.JP2 Clevels=6 Clayers=6 "Cprecincts={256,256},{256,256},{128,128}" "Stiles={512,512}" Corder=RPCL ORGgen_plt=yes ORGtparts=R "Cblk={64,64}" Cuse_sop=yes Cuse_eph=yes -flush_period 1024 Creversible=yes -rate –
~~~

My problem is that IIP fails to handle all the 16-bits images, whereas all the 8-bits images work as expected. I should note that all the images are valid JP2 files according to Jpylyzer. The only thing in common between the images that are problematic is the 16-bits channel...

Apache is throwing a 500 error when trying to handle a IIIF image request on these images:

```
[Mon Jul 15 23:34:35.139334 2019] [fcgid:warn] [pid 5240] [client 12.34.567.89:52829] mod_fcgid: error reading data, FastCGI server closed connection
[Mon Jul 15 23:34:35.139451 2019] [core:error] [pid 5240] [client 12.34.567.89:52829] End of script output before headers: iipsrv.fcgi
[Mon Jul 15 23:34:41.051897 2019] [fcgid:error] [pid 5232] mod_fcgid: process /var/www/iipsrv/iipsrv.fcgi(28485) exit(communication error), get unexpected signal 11
```

(I did not manage to enable more verbose logging, even though I have VERBOSITY set to 9 in my virtualhost...)

I have attached the Jpylyzer report for one of the image that raises this issue.

IIP is supposed to support images with 8, 16 and 32 bits per channel, so it strikes me that there might be a problem with that...

Does this have anything to do with the encoding of the source image? Any idea of what could go wrong?

Thanks a lot for your help.

**Comment by ruven** [comment]
I tried encoding a 16 bit image with your command and it works fine for me. Could you send me one of the problematic images to try out?

**Comment by regisrob** [comment]
Thanks Ruven for taking a look at it, I've just sent you an email with 2 problematic images.
I'll try to enable more verbose logging in the iipsrv log file...

**Comment by regisrob** [comment]
Closing this ticket... It was just a problem with the version of the IIP codebase being used
