### ISSUE TITLE
Ubuntu/apt-get version is out of date? Downloads 1.0-3 but latest is 1.1?

### ISSUE THREAD

**Issue by edant92** [ruven/iipsrv#174]
When I download iipimage-server via apt-get it downloads 1.0-3. 
`sudo apt-get install -y iipimage-server`

When I then run `apt-cache policy iipimage-server` I get the following:
```
iipimage-server:
  Installed: 1.0-3
  Candidate: 1.0-3
  Version table:
 *** 1.0-3 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

According to https://iipimage.sourceforge.io/2019/06/iipsrv-1-1-released/. The latest version is 1.1. How can I download this? Or am I interpreting this incorrectly?

Thanks

**Comment by ruven** [comment]
Debian Bullseye is indeed based on iipsrv 1.1: https://packages.debian.org/bullseye/iipimage-server

Unfortunately it looks like the Ubuntu packages haven't been synchronized yet with this latest version. It will eventually be updated, but in the meantime if you want, it's easy to build iipsrv 1.1 from source.

**Comment by edant92** [comment]
Thanks for clarifying!
