### ISSUE TITLE
Unusual characters in URL - escape?

### ISSUE THREAD

**Issue by Knurg** [ruven/iipsrv#180]
I am running iip-server as IIIF-Backend for high resolution tif images. One of the files has a + character in its file name and it seems not to be delivered correctly:
https://tafelmalerei.gnm.de/fcgi-bin/iipsrv.fcgi?IIIF=/srv/www/htdocs/sites/default/files/styles/wisski_pyramid/public/2018-07/Gm1161+1187_XR_WissKI_0.tif/info.json

The file itself however is there and valid:
server-tafelmalerei:/srv/www/htdocs/sites/default/files/styles/wisski_pyramid/public/2018-07 # ls -l /srv/www/htdocs/sites/default/files/styles/wisski_pyramid/public/2018-07/Gm1161\+1187_XR_WissKI_0.tif
-rwxrwxrwx 1 root root 93872197 Dec 17  2018 /srv/www/htdocs/sites/default/files/styles/wisski_pyramid/public/2018-07/Gm1161+1187_XR_WissKI_0.tif

As everything else is working, I guess the + is the problem. However I don't know how to escape it.

Thanks in advance,

Mark

**Comment by JoeTo1** [comment]
double encode the + 
%252B

**Comment by ruven** [comment]
Yes, thanks @JoeTo1 double encoding works fine:

https://tafelmalerei.gnm.de/fcgi-bin/iipsrv.fcgi?IIIF=/srv/www/htdocs/sites/default/files/styles/wisski_pyramid/public/2018-07/Gm1161%252B1187_XR_WissKI_0.tif/info.json

For IIP FIF commands, just a single encoding with %2B is sufficient:

https://tafelmalerei.gnm.de/fcgi-bin/iipsrv.fcgi?FIF=/srv/www/htdocs/sites/default/files/styles/wisski_pyramid/public/2018-07/Gm1161%2B1187_XR_WissKI_0.tif&WID=500&CVT=JPEG

**Comment by Knurg** [comment]
Thanks for the fix.

The info.json works well now:
https://tafelmalerei.gnm.de/fcgi-bin/iipsrv.fcgi?IIIF=/srv/www/htdocs/sites/default/files/styles/wisski_pyramid/public/2018-07/Gm1161%252B1187_XR_WissKI.tif/info.json

But in there it refers to:
https://tafelmalerei.gnm.de/fcgi-bin/iipsrv.fcgi?IIIF=/srv/www/htdocs/sites/default/files/styles/wisski_pyramid/public/2018-07/Gm1161%2B1187_XR_WissKI.tif

And this fails the loads for mirador as a consequence - it would have to be
https://tafelmalerei.gnm.de/fcgi-bin/iipsrv.fcgi?IIIF=/srv/www/htdocs/sites/default/files/styles/wisski_pyramid/public/2018-07/Gm1161%252B1187_XR_WissKI.tif

Best

Mark


Am Fr., 6. März 2020 um 15:40 Uhr schrieb Ruven <notifications@github.com>:
