### ISSUE TITLE
Coredump on large image

### ISSUE THREAD

**Issue by atiro** [ruven/iipsrv#181]
A largeish image (64838 by 41363) is throwing a coredump when requested at full size ("full/full/0/default.jpg"). Smaller size requests work upto 126 pixels and then break ("/full/126,/0/default.jpg"). The memory error being thrown in both cases is:

*** Error in `/srv/iipimage1.1/fcgi-bin/iipsrv.fcgi': munmap_chunk(): invalid pointer: 0x00000000010c8b60 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f73cafc37e5]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7f73cafd0698]
/srv/iipimage1.1/fcgi-bin/iipsrv.fcgi[0x412ffb]
/srv/iipimage1.1/fcgi-bin/iipsrv.fcgi[0x4136ac]
/srv/iipimage1.1/fcgi-bin/iipsrv.fcgi[0x4142f7]
/srv/iipimage1.1/fcgi-bin/iipsrv.fcgi[0x41603a]
/srv/iipimage1.1/fcgi-bin/iipsrv.fcgi[0x42e8e0]
/srv/iipimage1.1/fcgi-bin/iipsrv.fcgi[0x43b057]
/srv/iipimage1.1/fcgi-bin/iipsrv.fcgi[0x409115]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f73caf6c830]
/srv/iipimage1.1/fcgi-bin/iipsrv.fcgi[0x40c349]
======= Memory map: ========
00400000-00453000 r-xp 00000000 fc:00 657435                             /srv/iipimage1.1/fcgi-bin/iipsrv.fcgi
00652000-00653000 r--p 00052000 fc:00 657435                             /srv/iipimage1.1/fcgi-bin/iipsrv.fcgi
00653000-00654000 rw-p 00053000 fc:00 657435                             /srv/iipimage1.1/fcgi-bin/iipsrv.fcgi
00654000-00655000 rw-p 00000000 00:00 0 
0104e000-01119000 rw-p 00000000 00:00 0                                  [heap]

**Comment by atiro** [comment]
Should have also said, it's a grayscale image (Infra-Red) and the info.json request is fine.

**Comment by ruven** [comment]
What does it say in the iipsrv log file?

I just tried with an image of the same size and it works fine on a machine with enough memory to handle this. If there isn't enough memory, it should send out an error without crashing. In fact I just pushed a new commit, 3fc1437c1aa02862dfd70e0e52f90fd76529295f, which includes better memory error reporting, which you may want to try.

**Comment by atiro** [comment]
Hi @ruven I *think* now it might be a very strange incomplete file so nothing to do with IIpsrv, it looks like imagemagick ran out of disc space while building the pyramid tiff. I'm slightly amazed anything was created at all and that iipsrv is still reading the tiff and trying to make sense out of it. I'm just re-converting the image and will update/close this issue tomorrow if that's the cause.

**Comment by ruven** [comment]
iipsrv shouldn't crash on malformed files. If you still have the file, I'd be interested to see what it says in the iipsrv log just before the crash

**Comment by atiro** [comment]
Sorry @ruven I should have closed this ages ago. Apologies I've lost the image and logs since then. Will re-open if back in same situation.
