### ISSUE TITLE
Corrupted tile with COL=BINARY

### ISSUE THREAD

**Issue by sbarex** [ruven/iipsrv#183]
Requesting a tile with `COL=BINARY` return raw data and not a jpeg compressed file (the rawtile.compressionType result set to JPEG when outputting the data, so is not recompressed). 
IIPSRV works correctly if passing other arguments such `CNT` (!=1) or `ROT` (!=0) (for example `ROT=90&COL=BINARY`).
`COL=GRAY` works correctly..

The problem don't occours extracting all image with `CVT`.

See #184

**Comment by ruven** [comment]
Fixed: https://github.com/ruven/iipsrv/commit/5c043f3f796dd26acf9e3e92884d047aa3633e11
