### ISSUE TITLE
Unable to request full image width and height

### ISSUE THREAD

**Issue by ahankinson** [ruven/iipsrv#186]
By default, if MAX_CVT is not set, the maximum width and height requestable is 5000 pixels. Setting MAX_CVT to `-1` clamps the maximum to 64 pixels. Between those two settings it is not possible (without setting some astronomically high size) to request the full native size of an image.

Would it be possible to change it so that:

MAX_CVT >= 0 < 64, max size is 64
MAX_CVT is not set, max size is 5000
MAX_CVT < 0, (e.g., -1) then no maximum size is set

That should match the expected behaviours now, with the benefit of being able to disable this functionality completely.

**Comment by ruven** [comment]
Yes, this sounds more logical. Currently the minimum size is 64 pixels - perhaps we should allow smaller sizes, down to 1 pixel even to give a maximum of flexibility.

It's an easy change to make - I'll push a commit that does this soon.

**Comment by ahankinson** [comment]
Thanks, Ruven! You can currently [request an image](https://iiif.bodleian.ox.ac.uk/iiif/image/ef9f6292-eef3-4ce5-9273-c20a998152c1/full/32,/0/default.jpg) smaller than 64px. I'm not sure what the use case would be for allowing a maximum single image size of 1px would be, though. Among other things that would be very strange for tile servers to handle, since they would need to request every single pixel as its own 'tile'.

**Comment by ruven** [comment]
You can currently even request an image of 1px in size! https://iiif.bodleian.ox.ac.uk/iiif/image/ef9f6292-eef3-4ce5-9273-c20a998152c1/full/1,/0/default.jpg

Pure tile requests, however, are not currently subject to limits from MAX_CVT. It only affects image exports. Using IIP commands, this means only CVT= requests are limited in this way. For IIIF, it's a bit more ambiguous, but if the server determines that the request is for an aligned tile, it won't be limited by MAX_CVT.

Anyway, it's no doubt good to let iipsrv administrators choose whatever maximum they want - even down to 1px!

**Comment by ahankinson** [comment]
I've just tested this on our setup (iipsrv 1.1):

Currently if I set MAX_CVT to -1 and I request a 'tile' of 256 pixels wide from a region of 512x512, the maximum tile size I can get back is 64x64.

In other words, a request for: 

`/iiif/image/ef9f6292-eef3-4ce5-9273-c20a998152c1/0,0,512,512/256,/0/default.jpg`

will only ever return a maximum tile size of 64x64. I think most IIIF viewers use the `tiles` property to set their requestable tile sizes, so they'll be asking for 256wh tiles, but only receiving 64wh. 

I think. :)

**Comment by ahankinson** [comment]
It's probably because although the request is run through the JTL handler, the requested image sizes *are* clamped in reference to the max_CVT values (`max_size` is set from the max_CVT value, I believe):

https://github.com/ruven/iipsrv/blob/master/src/IIIF.cc#L408-L418

**Comment by ruven** [comment]
You're right, it's in fact clamped before it gets to the JTL handler and as the sizes have been clamped in this way, the request will be handled instead by the CVT code.

Well, I think I'll keep this behaviour for IIIF. It's more consistent as there isn't really a distinct concept of a "tile" in IIIF.

**Comment by ruven** [comment]
OK, try this commit. It should work as you want. Minimum is 1px and setting it to -1 disables any limit: https://github.com/ruven/iipsrv/commit/26a27b15328f20d6462ced814e84768ec5bfe3bd

**Comment by ahankinson** [comment]
Thanks Ruven! We tested it this morning and it seems to work as expected.

**Comment by ruven** [comment]
Great! I'll close this issue. Let me know if any issues arise.
