### ISSUE TITLE
Compile error with Visual Studio 2010 Express

### ISSUE THREAD

**Issue by tmtisfree** [ruven/iipsrv#188]
Visual Studio 2010 Express reports this error:

> 1>..\src\View.cc(41): error C2668: 'floor' : ambiguous call to overloaded function
1>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(567): could be 'long double floor(long double)'
1>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(519): or       'float floor(float)'
1>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(136): or       'double floor(double)'
1>          while trying to match the argument list '(unsigned int)'

at this line:

https://github.com/ruven/iipsrv/blob/84c68147dd8bc4b763323a47e1d82ed72cf8cf2f/src/View.cc#L41

**Comment by ruven** [comment]
Thanks for spotting this. Should work now: https://github.com/ruven/iipsrv/commit/958d212b46f62aa9eaf8611f6c3cdef431451f2e

**Comment by tmtisfree** [comment]
Yes this is working now, thanks.
