### ISSUE TITLE
Home page returns HTTP 400

### ISSUE THREAD

**Issue by scossu** [ruven/iipsrv#190]
I am setting up a health-check service for my iipsrv instance. I noticed that the home page (the one with the intro text "IIPImage Server / Version x.y / Project Home Page [...]") is returning a `400 Bad Request`. 

Is this intentional? If it is, which other endpoint can I use for a health-check request that does not depend on backend data?

**Comment by ruven** [comment]
It's set to a 400 because an empty request is considered by iipsrv to be an error. But you're right that this means there's no readily available health-check URL. I could either make "homepage" request a valid request with a 200 response or perhaps even create a new server-status type URL. What do you think?

**Comment by scossu** [comment]
Unless you have a specific use in mind for the 400 page, I lean toward a non-error front page, i.e. simply changing the response code of the current page to 200 (after all it's the first place you would go to check a fresh install). 

A health-check page may be more complete but I wonder if it is worth while, since iipsrv doesn't seem to have any dependency on other network services.

**Comment by ruven** [comment]
OK, home page requests now return a HTTP 200 code: https://github.com/ruven/iipsrv/commit/94460a4291ca05a01de603661df1527b0da60826

**Comment by scossu** [comment]
Nice! Just out of  curiosity, I see that in [Main.cpp](https://github.com/ruven/iipsrv/commit/94460a4291ca05a01de603661df1527b0da60826#diff-d0b88177f233cffab982ea06b78a93bfR644) you are still throwing an exception. Is that handled internally without raising an HTTP error?

**Comment by ruven** [comment]
Yes, string exceptions are just output to the client with whatever status code you have set. The various types of exceptions are all handled towards the end of Main.cc

https://github.com/ruven/iipsrv/blob/94460a4291ca05a01de603661df1527b0da60826/src/Main.cc#L803

It's just a convenient way to handle various errors in a single location and output the appropriate HTTP status code.
