### ISSUE TITLE
Tile request errors new to version 1.1

### ISSUE THREAD

**Issue by seanaery** [ruven/iipsrv#198]
Hello @ruven --

For years, we have been using iipsrv version 1.0 to serve thousands of images in the Duke Digital Repository (e.g., https://repository.duke.edu/dc ), and it has been a dependable and highly valuable part of our infrastructure.

We recently updated iipsrv to version 1.1, and encountered issues loading individual tiles for a subset of our images (likely < 1%). These problems are not present when using 1.0, so we rolled back.

Here is a screenshot demonstrating the issue (using Openseadragon viewer). Some tiles remain grainy no matter the zoom level--http requests for the respective tiles fail--while others are clear. There are no problems with http requests for composite JPGs at any size; it's only happening for some tile requests, for some images.
<img width="1423" alt="ahslt010140010-iipsrv-1 1-tile-bug" src="https://user-images.githubusercontent.com/3933756/77662910-cf0da200-6f52-11ea-9b56-7857d7b335c6.png">

Here are three example image files that exhibit this problem using iipsrv 1.1. I have included the original TIF plus the compressed pyramidal TIF of each: https://duke.box.com/s/huiydxcjvs24owzoombtnioc7b5ankre

PTIFs were creating using ImageMagick e.g.:
`convert filename.tif -define tiff:tile-geometry=256x256 -compress jpeg -quality 90 ptif:filename.ptif`

By contrast (in case it's helpful), here are two example image files of ours that do NOT exhibit the problem; the tiling works fine in both 1.0 & 1.1:
https://duke.box.com/s/nzc7ylefp2mx17r6ynd4cfq4qa1hends

Is this a known issue with 1.1? Is there some characteristic of these images that is throwing off the tile calculations?

**Comment by ahankinson** [comment]
The 'box' links are set to be private.

**Comment by seanaery** [comment]
My apologies, @ahankinson , I've just corrected the settings to make those links publicly accessible. Thanks for taking a look.

**Comment by ruven** [comment]
It's in fact your ICC profiles which are causing the problem. As of version 1.1, these are embedded by default in the JPEG tiles. However, the ones causing problems to you are rather large (669057 bytes for ahslt010140010.tif) and are causing iipsrv to output corrupted JPEGs.

It's possible to embed large profiles into JPEG, so there must be something wrong somewhere in the iipsrv JPEG encoder code. I'll try to debug this and get back to you. But, a quick fix for you would be for you to simply disable ICC embedding by using setting EMBED_ICC=0 in your iipsrv 1.1 configuration.

**Comment by seanaery** [comment]
@ruven That's fantastic -- thank you so much for the thorough analysis and recommendation for a workaround. Much appreciated!

**Comment by ruven** [comment]
I've committed some changes (https://github.com/ruven/iipsrv/commit/c58f206cd9b67d73490998bb1709358f2d8806cb) that should fix this issue and should now allow iipsrv to work with images with arbitrary sized profiles.

Please try it out and let me know if there's still a problem.

**Comment by seanaery** [comment]
@ruven Sorry for the delayed response. I have finally tried this out and can confirm that your revisions in [c58f206](https://github.com/ruven/iipsrv/commit/c58f206cd9b67d73490998bb1709358f2d8806cb) did indeed fix the problem. Thank you so much for resolving that issue so quickly!

**Comment by ruven** [comment]
No worries - thanks for confirming it works!
