### ISSUE TITLE
IIIF Requests with negative numbers return MAX_CVT size images 

### ISSUE THREAD

**Issue by ahankinson** [ruven/iipsrv#201]
When issuing a IIIF request with negative numbers in the width, height field, IIP will return an image that is sized to MAX_CVT. For example:

https://iiif.bodleian.ox.ac.uk/iiif/image/35940a43-ee1f-4642-8a3b-4e38399a3378/full/!-2,-3/0/default.jpg

This will return an image that is 750x1000 pixels. 

This is true even if the original image size is less than MAX_CVT. On our internal testing server we see that an image that is 5412x7216 will be upscaled to MAX_CVT of 20,000, resulting in an image of 15000x20000.

**Comment by ruven** [comment]
According to the [IIIF size parameter specs](https://iiif.io/api/image/3.0/#42-size), this should return an error, so I've modified it to do that.

**Comment by ahankinson** [comment]
Thank you!
