### ISSUE TITLE
Wrong resolution being used when requesting tiles

### ISSUE THREAD

**Issue by dthornley** [ruven/iipsrv#202]
I have a jp2 image (4095x2500) that I'm viewing via the IIIF protocol.
[test_0001.jp2.gz](https://github.com/ruven/iipsrv/files/4896485/test_0001.jp2.gz) (gziped)

When I request tiles from any image of this size (4095 wide) I'm getting the wrong tile for the right hand side of the image. For example requesting the tile for .../2048,0,2047,2048/256,/0/default.jpg returns the following image 

![wrong_tile](https://user-images.githubusercontent.com/1854363/87036238-c9c72100-c1ea-11ea-92dd-3a1141aed5c6.jpg)
instead of the expected image 

![expected_tile](https://user-images.githubusercontent.com/1854363/87036256-d2b7f280-c1ea-11ea-913a-7978605c11a2.jpg)

The other 3 tiles for this resolution are all correct.

After investigating I discovered that the solution suggested for issue #189 (pull request #196) seems to also fix my issue.

This is present in the latest version of master d4a701864877cb22ec6212c284ccd733ce3106d8.

**Comment by ruven** [comment]
This indeed looks fixed in https://github.com/ruven/iipsrv/pull/196, which is now merged
