### ISSUE TITLE
Compile error with Visual Studio 2010 Express

### ISSUE THREAD

**Issue by tmtisfree** [ruven/iipsrv#205]
Doing my annual build of iipsrv, there is an error in JPEGCompressor.cc:

> 1>..\..\src\JPEGCompressor.cc(226): error C3861: 'round' : identificateur introuvable
> 1>..\..\src\JPEGCompressor.cc(227): error C3861: 'round' : identificateur introuvable
> 1>..\..\src\JPEGCompressor.cc(394): error C3861: 'round' : identificateur introuvable
> 1>..\..\src\JPEGCompressor.cc(395): error C3861: 'round' : identificateur introuvable

I resolve the issue by copying in JPEGCompressor.cc the following code from Transform.h:

```
// Define round() function for older MSVC compilers
#if defined _MSC_VER && _MSC_VER<1900
inline double round(double r) { return (r > 0.0) ? floor(r + 0.5) : ceil(r - 0.5); }
#endif

```

There are also the usual bunch of warnings that don't seem to matter much though:

> 1>..\src\IIIF.cc(407): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
> 1>..\src\IIIF.cc(408): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
> 1>..\src\IIIF.cc(431): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
> 1>..\src\IIIF.cc(441): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
> 1>..\src\IIIF.cc(473): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
> 1>..\src\IIIF.cc(477): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
> 1>  JTL.cc
> 1>..\src\JPEGCompressor.cc(231): warning C4244: '=' : conversion from 'double' to 'UINT16', possible loss of data
> 1>..\src\JPEGCompressor.cc(232): warning C4244: '=' : conversion from 'double' to 'UINT16', possible loss of data
> 1>..\src\JPEGCompressor.cc(399): warning C4244: '=' : conversion from 'double' to 'UINT16', possible loss of data
> 1>..\src\JPEGCompressor.cc(400): warning C4244: '=' : conversion from 'double' to 'UINT16', possible loss of data
> 1>  KakaduImage.cc
> 1>  Main.cc
> 1>  OBJ.cc
> 1>  PFL.cc
> 1>..\src\KakaduImage.cc(190): warning C4244: '=' : conversion from 'double' to 'unsigned int', possible loss of data
> 1>..\src\KakaduImage.cc(191): warning C4244: '=' : conversion from 'double' to 'unsigned int', possible loss of data
> 1>..\src\KakaduImage.cc(208): warning C4244: '=' : conversion from 'double' to 'unsigned int', possible loss of data
> 1>..\src\KakaduImage.cc(209): warning C4244: '=' : conversion from 'double' to 'unsigned int', possible loss of data
> 1>..\src\KakaduImage.cc(488): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
> 1>  SPECTRA.cc
> 1>  Task.cc
> 1>  TIL.cc
> 1>  TileManager.cc
> 1>  TPTImage.cc
> 1>  Transforms.cc
> 1>..\src\TPTImage.cc(162): warning C4805: '==' : unsafe mix of type 'bool' and type 'double' in operation
> 1>..\src\Transforms.cc(1010): warning C4244: '=' : conversion from 'unsigned int' to 'float', possible loss of data
> 1>  View.cc
> 1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xutility(2692): warning C4244: '=' : conversion from 'const double' to 'float', possible loss of data
> 1>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xutility(2715) : see reference to function template instantiation 'void std::_Fill<_Iter,_Ty>(_FwdIt,_FwdIt,const _Ty &)' being compiled
> 1>          with
> 1>          [
> 1>              _Iter=float *,
> 1>              _Ty=double,
> 1>              _FwdIt=float *
> 1>          ]
> 1>          ..\src\Transforms.cc(1003) : see reference to function template instantiation 'void std::fill<float*,double>(_FwdIt,_FwdIt,const _Ty &)' being compiled
> 1>          with
> 1>          [
> 1>              _FwdIt=float *,
> 1>              _Ty=double
> 1>          ]
> 1>  Watermark.cc
> 1>  Zoomify.cc
> 1>..\src\Watermark.cc(73): warning C4244: '=' : conversion from 'float' to 'unsigned char', possible loss of data
> 1>..\src\Watermark.cc(74): warning C4244: '=' : conversion from 'float' to 'unsigned char', possible loss of data
> 1>..\src\Watermark.cc(75): warning C4244: '=' : conversion from 'float' to 'unsigned char', possible loss of data
> 1>..\src\Watermark.cc(106): warning C4244: '=' : conversion from 'float' to 'unsigned int', possible loss of data
> 1>..\src\Watermark.cc(112): warning C4244: '=' : conversion from 'float' to 'unsigned int', possible loss of data
> 1>..\src\View.cc(66): warning C4244: 'argument' : conversion from 'float' to 'unsigned int', possible loss of data
> 1>..\src\View.cc(67): warning C4244: 'argument' : conversion from 'float' to 'unsigned int', possible loss of data
> 1>..\src\View.cc(183): warning C4244: 'initializing' : conversion from 'double' to 'unsigned int', possible loss of data
> 1>..\src\View.cc(191): warning C4244: 'initializing' : conversion from 'double' to 'unsigned int', possible loss of data
>

**Comment by ruven** [comment]
OK, thanks. I added your fix in this commit: https://github.com/ruven/iipsrv/commit/66452277fc1d1577fe3357334ee33d2d4311ac3e

You're right about the warnings - you don't need to worry about them.
