### ISSUE TITLE
IIP crashes when trying to fetch cached image

### ISSUE THREAD

**Issue by filak** [ruven/iipsrv#208]
When I first access http://iip.test/fcgi-bin/iipsrv.fcgi?FIF=/test2.jp2&HEI=700&CVT=jpeg - the image is rendered fine, but when I click reload button I get 500 error, when reloading again the image renders fine, then 500 status again...

When I disable browser caching, the image reloads fine all the time.

IMHO the IIP fcgi app breaks/restarts when trying to fetch the cached image - if it had been really cached before. 

I have tried turning off/on Memcached but this does not have any effect.

IIP log:
```
Fri Mar 26 18:04:47 2021

IIPImage Server. Version 1.1
*** Ruven ... ***

Verbosity level set to 10
Running in FCGI mode

Setting maximum image cache size to 500MB
Setting filesystem prefix to 'c:/Data/iip-data/'
Setting default JPEG quality to 90
Setting maximum CVT size to 3500
Setting HTTP Cache-Control header to 'max-age=86400'
Setting 3D file sequence name pattern to '_pyr_'
Setting max quality layers (for supported file formats) to all layers
Setting Allow Upscaling to true
Setting ICC profile embedding to true
Setting up JPEG2000 support via OpenJPEG
Setting image processing engine to CPU processor


Initialisation Complete.
<----------------------------------->

Full Request is FIF=/test2.jp2&HEI=700&CVT=jpeg
[1/3]: Command / Argument is FIF : /test2.jp2
FIF handler reached
FIF :: URL decoding/filtering: /test2.jp2 => /test2.jp2
FIF :: Image cache initialization
FIF :: JPEG2000 image detected
FIF :: Created image
FIF :: Image dimensions are 2575 x 3513
FIF :: Image contains 3 channels with 8 bits per channel
FIF :: Image timestamp: Tue, 30 Jan 2018 10:24:51 GMT
FIF :: Total command time 2000 microseconds
[2/3]: Command / Argument is HEI : 700
HEI handler reached
HEI :: requested height is 700
[3/3]: Command / Argument is CVT : jpeg
CVT :: JPEG output
CVT handler reached
CVT :: Using resolution 2 with size 643x878
CVT :: No view port set
CVT :: Requested scaled region size is 513x700. Nearest existing resolution is 2 which has region with size 643x878
TileManager getRegion :: requesting region directly from image
CVT :: Resizing using bilinear interpolation in 13000 microseconds
CVT :: About to compress strip with height 128
CVT :: Compressed data strip length is 22998
CVT :: About to compress strip with height 128
CVT :: Compressed data strip length is 25312
CVT :: About to compress strip with height 128
CVT :: Compressed data strip length is 26433
CVT :: About to compress strip with height 128
CVT :: Compressed data strip length is 25162
CVT :: About to compress strip with height 128
CVT :: Compressed data strip length is 21833
CVT :: About to compress strip with height 60
CVT :: Compressed data strip length is 10018
CVT :: Total command time 160000 microseconds
Total Request Time: 162000 microseconds
image closed and deleted
Server count is 1

Full Request is FIF=/test2.jp2&HEI=700&CVT=jpeg
HTTP Header: If-Modified-Since: Tue, 30 Jan 2018 10:24:51 GMT
[1/3]: Command / Argument is FIF : /test2.jp2
FIF handler reached
FIF :: URL decoding/filtering: /test2.jp2 => /test2.jp2
FIF :: Image cache hit. Number of elements: 1
FIF :: JPEG2000 image detected
FIF :: Created image
FIF :: Image dimensions are 2575 x 3513
FIF :: Image contains 3 channels with 8 bits per channel
FIF :: Image timestamp: Tue, 30 Jan 2018 10:24:51 GMT
<----------------------------------->
Fri Mar 26 18:24:51 2021

IIPImage Server. Version 1.1
*** Ruven ... ***
...
```
Apache log contains (but this is just aftermath):
```
[Fri Mar 26 18:29:50.479429 2021] [fcgid:warn] [pid 15680:tid 8412] (OS 109)The pipe has been ended.  : [client 127.0.0.1:49214] mod_fcgid: get overlap result error
[Fri Mar 26 18:29:50.480429 2021] [core:error] [pid 15680:tid 8412] [client 127.0.0.1:49214] End of script output before headers: iipsrv.fcgi
```

Environment:

IIPSRV 1.1 on Windows 7 Pro x64
Apache 2.4.46 from ApacheLounge with mod_fcgid 2.3.10 - I have tried both x64 and x32 versions with the same results.

Apache IIP config:
```
<VirtualHost iip.test:80>
  ServerName iip.test ## Mapped in etc\hosts as 127.0.0.1
  DocumentRoot "${IIPDATA}"

  <Directory "${IIPDATA}">
     Require all granted
  </Directory>

</VirtualHost>

ScriptAlias /fcgi-bin/ "${DATAROOT}/iipsrv/fcgi-bin/"

<Directory "${DATAROOT}/iipsrv/fcgi-bin/">
  Require all granted
  AddHandler fcgid-script .fcgi
</Directory>

FcgidIPCDir "${DATAROOT}/iipsrv/fcgidsock"

# Set our environment variables for the IIP server
FcgidInitialEnv FILESYSTEM_PREFIX "${IIPDATA}"
FcgidInitialEnv LOGFILE "${DATAROOT}/iipsrv/logs/iipsrv.log"
FcgidInitialEnv VERBOSITY "10"
FcgidInitialEnv MAX_IMAGE_CACHE_SIZE "500"
FcgidInitialEnv JPEG_QUALITY "90"
FcgidInitialEnv MAX_CVT "3500"
FcgidInitialEnv MAX_LAYERS "-1"
##FcgidInitialEnv MEMCACHED_SERVERS "127.0.0.1:55370"
FcgidInitialEnv ALLOW_UPSCALING "1"

FcgidIdleTimeout 0
FcgidMaxProcessesPerClass 1

```

**Comment by filak** [comment]
I can just confirm that the behavior is the same with IIIF:

http://iip.test/fcgi-bin/iipsrv.fcgi?IIIF=/test2.jp2/full/700,/0/default.jpg

**Comment by filak** [comment]
I had to disable the caching in Apache IIP vhost config to avoid IIP crashing
````
Header always set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
Header always set Pragma "no-cache" 
````

**Comment by tdeherdt** [comment]
For what it's worth: I have (what appears to be) the same problem with iipsrv1.1 running through IIS webserver on Windows 10. Runs perfectly fine, but hitting refresh or reload in the browser results in a 500 server error.

I managed to fix it by adding the HTTP headers you describe, so thank you @filak.

Still, I wonder if disabling caching is the right thing to do, i.e. this is somehow by design. If so, shouldn't this be described in installation documents?

**Comment by tdeherdt** [comment]
OK, I understand. Hopefully this can be fixed at some point. (I'm afraid I lack the skills to debug this.)

It would be interesting to know if this affects all Windows installations. Is anyone _not_ having this problem with the pre-built Windows binary?

**Comment by filak** [comment]
Well, I have managed to build the code in VS 2017 Community finally... I will put a guide on GitHub later.

If caching is enabled the server silently crashes (when repeatedly reloading the image) on this line: https://github.com/ruven/iipsrv/blob/39557f81f5a5b14a71a861fc2058bd4ecedc561c/src/FIF.cc#L229

strptime() seems not to be supported on Windows platform.

I am not able to debug this further as my knowledge of C is null - maybe @ruven might help on this?

**Comment by tdeherdt** [comment]
Thank you @filak for locating the issue, this is very helpful and brings us closer to a solution. I'm not familiar with C either, but a quick web search brings up alternative code for strptime(). Let's hope this thread reaches a developer willing to fix this, so iipsrv can be used on Windows.

**Comment by ruven** [comment]
Thanks @filak for tracking this down. My knowledge of Windows is rather limited, so, unfortunately, I wasn't able to bring any light to this issue earlier.

You are correct that strptime() is not supported on Windows. However, to get around this, the function is defined especially for Windows builds in [Time.h](https://github.com/ruven/iipsrv/blob/master/windows/Time.h) and [Time.cc](https://github.com/ruven/iipsrv/blob/master/windows/Time.cc). The implementation is based on one from another open source project, but maybe there's a problem with certain versions of Windows. I'll look into an alternative implementation and get back to you.

**Comment by filak** [comment]
Thanks @ruven. I have just finished the guide:

https://github.com/filak/IIPImage-on-Windows

Feel free to link to it from the docs as you see fit.

**Comment by ruven** [comment]
OK, I've managed to track down the cause of this and have committed a fix (https://github.com/ruven/iipsrv/commit/d400c64d9bc9bdc1e7673103fed9a75109aa7938). iipsrv now properly handles if-modified-since cached content on my test server. Please re-enable caching and test yourselves with the latest version of iipsrv and let me know if there are still any problems.

**Comment by filak** [comment]
OK, it needs to be:

     timeptr->tm_isdst = 0;

**Comment by ruven** [comment]
Oops, corrected: https://github.com/ruven/iipsrv/commit/f4073849942750718216b15ca741f9a71d09e403

So, is Memcached now working correctly with the #undef _WIN32 fix?

**Comment by filak** [comment]
Yes https://github.com/ruven/iipsrv/issues/226

This issue is also fixed, so I am closing this as well.
