### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by lromor** [ruven/iipsrv#210]
Hi,

nice project, I noticed that you try to follow the iiif specification. In the specification, there's a section about annotation lists:
https://iiif.io/api/presentation/2.1/#annotation-list

Are you planning to add such a feature?

**Comment by ruven** [comment]
IIIF consists of multiple API's that are usually handled by distinct components. IIPImage handles the **image API** and deals with images directly, whereas annotations are part of the **presentation API**, which concerns metadata which is usually handled by components within a database or CMS.

So, to answer your question, no, this is not something planned for iipsrv.

**Comment by lromor** [comment]
Ha! I didn't notice the APIs specifications were differentiated. Thank you for helping me to clarify.
