### ISSUE TITLE
Lossless image transfer

### ISSUE THREAD

**Issue by Aiosa** [ruven/iipsrv#211]
I was unable to find an option to disable JPEG compression on a served tiles. In my case, IIPImage is extracting `dzi` tiles from a pyramidal tiff, but the compression before the tile is actually sent introduces errors to post-processing done on the client-side (pixels are treated like data-based rather than visual-based information), not even `JPEG_QUALITY "100"` is sufficient. The most optimal would be to use URL parameters to specify whether compression is or is not allowed - is this possible? Thank you.

**Comment by ruven** [comment]
Is your TIFF uncompressed and you want access to the raw data? The thing is, the tiles need to be encoded into some sort of image format (or sent as raw data).

The JPEG format necessarily involves lossy compression. What you need is lossless compression through something like PNG, which would allow you to reconstruct this raw data precisely. I'll be integrating PNG export support shortly into the main branch, but in the meantime you could take a look a this fork: https://github.com/Cytomine-ULiege/iipsrv which has both PNG and TIFF output.

**Comment by Aiosa** [comment]
Yeah, PNG is probably the way to go. Thank you so much, will definitely have a look and look forward the integration :)

**Comment by ruven** [comment]
Lossless image output is now available through this commit which enables PNG output: https://github.com/ruven/iipsrv/commit/7cf3457461ffd403d5d8cd8b1b5f82e808cb95bb

It only outputs 8 bit PNGs for now, but I'll enable 16 bit output also soon.
