### ISSUE TITLE
Error when requesting PNG image

### ISSUE THREAD

**Issue by WardMaes** [ruven/iipsrv#217]
The server returns `IIIF :: unsupported output format` when requesting a png image using the IIIF protocol (`/fcgi-bin/iipsrv.fcgi?IIIF=<image-name>.jp2/full/max/0/default.png`). 

According to the logs, the IIIF API version is set to 3. 
`Setting default IIIF Image API version to 3`

After the `configure` step, the `PNG Output` option is enabled. 

```
Options Enabled:
---------------
 Memcached  :  false
 JPEG2000   :  true (Kakadu)
 OpenMP     :  true
 Loggers    :  file, syslog
 PNG Output :  true
```

What am I missing here?

**Comment by ruven** [comment]
Did you pull latest git commit over an existing build? Try doing a `make clean` or even` make distclean` before rebuilding.

**Comment by WardMaes** [comment]
I did, this fixed it. 
I didn't find anything about `make clean` or `make distclean` in the documentation so you might consider adding it (or maybe I missed it somewhere). 

Thanks a lot for the fast response!
