### ISSUE TITLE
"invalid width" when using IIIF 3.0 upscaling prefix

### ISSUE THREAD

**Issue by johndoe46** [ruven/iipsrv#222]
Hello,

Given the following IIIF spec:

> The size parameter specifies the dimensions to which the extracted region, which might be the full image, is to be scaled. With the exception of the w,h and ^w,h forms, the returned image maintains the aspect ratio of the extracted region as closely as possible. Sizes prefixed with ^ allow upscaling of the extracted region when its pixel dimensions are less than the pixel dimensions of the scaled region.

And URL in such form: https://domain.tld/path/to.image.tif/full/^300,/0/default.jpg which to me is ok with the following spec at https://iiif.io/api/image/3.0/ :

> ^w, | The extracted region should be scaled so that the width of the returned image is exactly equal to w. If w is greater than the pixel width of the extracted region, the extracted region is upscaled.

Using the ^ prefix generates a HTTP 400 Bad Request with "invalid width" in the body. Removing the upscaling prefix ^, the image is fine (but not upscaled obviously).

I first thought I made a mistake but I couldn't reproduce such behaviour with Cantaloupe (which in fact will generate an error if the requested width is bigger than the original image and so effectively requires to have the upscaling prefix in such case).

Is this a bug or am I doing something wrong ?

Thank you for your light on this matter.

**Comment by ruven** [comment]
What version of iipsrv are you using? The ^ prefix is a recent addition to the IIIF specification and only appears in version 3 of the Image API, so you'll need to make sure you are using the latest iipsrv source code from Github and not the last official 1.1 release.

If you are in fact using the latest iipsrv code, then make sure you set the IIIF_VERSION startup variable to 3, as it defaults to version 2 for compatibility reasons.

**Comment by johndoe46** [comment]
Hello @ruven ,

Thanks for your quick answer.

Indeed, we were using official 1.1 in production, so that explains it all.

We just compiled a more recent version and it works just as intended. Closing this now.

Thank you !
