### ISSUE TITLE
1.2 release

### ISSUE THREAD

**Issue by jbschrantz** [ruven/iipsrv#230]
Hello Ruven,

Thank you for your amazing work.
Our installer is using the following command to install iipsrv stable release 1.1:
`git clone https://github.com/ruven/iipsrv.git`
Since a few days the same command install version 1.2 while there is no 1.2 release yet !
Should we use another link ?

Also we notice that the ./full/full /... access does not work anymore on 1.2.
Thank you for your feedback

**Comment by ruven** [comment]
The Github version is the current rolling development version, but which is (should be), nonetheless, stable. The last official stable release is 1.1, which you can get from here: [https://github.com/ruven/iipsrv/archive/refs/tags/iipsrv-1.1.tar.gz](https://github.com/ruven/iipsrv/archive/refs/tags/iipsrv-1.1.tar.gz). It's been re-tagged as 1.2 in preparation of an official 1.2 release, which should happen fairly soon.

/full/full/ should still work fine. Note that version 3 of the IIIF Image API deprecates _full_ in favour of _max_ for the size parameter, but iipsrv will support both. Perhaps you have an export size limit set through the MAX_CVT start-up parameter? If not, send me the section of the iipsrv log file where this is not working properly and I'll have a look.

**Comment by ruven** [comment]
Version 1.2 now officially released: https://github.com/ruven/iipsrv/releases/tag/iipsrv-1.2
