### ISSUE TITLE
New user experience - missing Webp

### ISSUE THREAD

**Issue by killerwife** [ruven/iipsrv#240]
Hey just want to give some feedback to a missing thing.

I used https://iipimage.sourceforge.io/documentation/server/windows/ to set it up.

When done this way with new clone, it will cry that you do not have Webp installed, which is an optional feature, but I guess you make everything mandatory with the premade .sln, which is fine. However would be great to add a mention of it to the windows installation guide about webp, perhaps which vcpkg package or which repository to download.

If I did a mistake somewhere, then let me know, maybe someone will see this issue as a result of the same mistake.

I made it work for myself by removing the preprocessor define and adding some additional ifdefs to some files. (which should be harmless otherwise) I just cant imagine thats meant to be the new user experience :D Cheers.

**Comment by ruven** [comment]
Thanks for letting me know!

Webp is a very recent addition to iipsrv - looks like I forgot to update the docs accordingly. I've just corrected it now. To get it compile, you should only need to add libwebp to the vcpkg install command:

`\vcpkg.exe install tiff openjpeg fastcgi libpng libwebp --triplet x64-windows`

The rest of the compile should now work fine with the default .sln file.

**Comment by killerwife** [comment]
Amazing, closing the issue then, since this resolves it completely.
