### ISSUE TITLE
Apache configuration typo

### ISSUE THREAD

**Issue by killerwife** [ruven/iipsrv#242]
Page https://iipimage.sourceforge.io/documentation/server/windows/

The section following "To configure iipsrv, for example, with Apache Haus, open the httpd-fcgid.conf file within the conf\extra sub-folder and replace the contents with the following:" has 

<\IfModule>

When setting up on windows it did not work, and when consulting official apache conf from fastcgi module its written as:

</IfModule>

which fixed the issue for me. Mod FCGID 2.3.9a for Apache 2.4.x x64 was the one I used to setup things for myself and the conf example is therein.

**Comment by killerwife** [comment]
Derp, mustve picked up as some escape char. Basicallt the ifmodule slash is meant to be / not \

**Comment by ruven** [comment]
OK, now corrected! And thanks for your help in fixing the documentation! Much appreciated.
