### ISSUE TITLE
Question: Manifest.json

### ISSUE THREAD

**Issue by killerwife** [ruven/iipsrv#243]
Bit of a noob question,

what is the recommended approach to manifest.json generation. Trying to delve into IIIF and the problem is that it seems it has to be manually produced for any image (as only info.json is automatically generated)

**Comment by regisrob** [comment]
IIPImage is an image server and thus only deals with the IIIF Image API, basically by delivering pixels in a way that conforms to this protocol: https://iiif.io/api/image/ (see the [playground](https://www.learniiif.org/image-api/playground)).

IIIF Manifests encapsulate descriptive metadata and structural information of a digital object (that can consist of multiple images): it is about providing the context of the object being viewed, the ordering of images, and potentially additionnal resources associated with the object as annotations: see https://iiif.io/get-started/how-iiif-works/. Manifests files can be made by hand (see the Manifests editors) but they are generally produced dynamically as part of a process which combines descriptive information about the object (e.g. metadata extracted from a catalogue or whatever database) and information about the images (sequence, sizes, labels...). See https://github.com/IIIF/awesome-iiif/#presentation-manifest-tools

**Comment by killerwife** [comment]
Appreciate the info, will dig through it.
