### ISSUE TITLE
Options build on Alma 9 CentOS

### ISSUE THREAD

**Issue by killerwife** [ruven/iipsrv#244]
Need some troubleshooting advice. Compiling iipsrv with intention of adding optional modules. On windows it worked as a charm. However, after installing libmemcached and memcached, and libpng and libwebp on CentOS, the ./configure (even tried --enable-modules) does not detect these modules. Is there a setting needed to enable these so that configure detects them properly?

```
Options Enabled:
---------------
 Memcached   :  false
 JPEG2000    :  true (OpenJPEG)
 OpenMP      :  true
 Loggers     :  file, syslog
 PNG Output  :  false
 WebP Output :  false
 ```

I end up seeing this and its clear they are not in the build process. Apologize if I didn't find it in the documentation, I tried to scour through it and found nothing.

On a different feedback note, the fact that the windows folders "Visual Studio 2017" have a whitespace in them is really *** :D I know it looks better but you end up having to add quotes everywhere.

Appreciate any feedback on this, since the compile with these optional features works on windows, I reckon I am missing something and its not inherently problem of the project files.

**Comment by ruven** [comment]
I think it's just that you are missing the libpng and libwebp development headers on your machine. For CentOS you need to install the `libmemcached-devel`, `libpng-devel` and `libwebp-devel` packages. You can do that using yum:

`yum install libmemcached-devel libpng-devel libwebp-devel`

Then rerun the iipsrv ./configure script and it should work

**Comment by killerwife** [comment]
I installed the non -devel once, which is hillarious since on other distros where I support c++ software I always install those accordingly. Appreciate the help, all worked.
