### ISSUE TITLE
IIIF info.json uri of @id change to https

### ISSUE THREAD

**Issue by chinazhangbo** [ruven/iipsrv#247]
when open with url ：http://localhost:8011/iipsrv.fcgi?iiif=images/2.tif/info.json 
but response like this:
{
  "@context" : "http://iiif.io/api/image/2/context.json",
  "@id" : "https://localhost:8011/iipsrv.fcgi?iiif=images/2.tif",
  "protocol" : "http://iiif.io/api/image",
  "width" : 640,
  "height" : 390,
  "sizes" : [
     { "width" : 80, "height" : 48 },
     { "width" : 160, "height" : 97 },
     { "width" : 320, "height" : 195 }
  ],
  "tiles" : [
     { "width" : 256, "height" : 256, "scaleFactors" : [ 1, 2, 4, 8 ] }
  ],
  "profile" : [
     "http://iiif.io/api/image/2/level1.json",
     { "formats" : [ "jpg" ],
       "qualities" : [ "native","color","gray","bitonal" ],
       "supports" : ["regionByPct","regionSquare","sizeByForcedWh","sizeByWh","sizeAboveFull","rotationBy90s","mirroring"],
       "maxWidth" : 5000,
       "maxHeight" : 5000
     }
  ]
}

the @id  key‘s value contain https ，i think should be http

**Comment by ruven** [comment]
Are you using version 1.1 of the server? This works correctly when using the latest version of the code from Github.

**Comment by chinazhangbo** [comment]
yes, i am using version 1.1, thanks
