### ISSUE TITLE
When will the next version be released

### ISSUE THREAD

**Issue by chinazhangbo** [ruven/iipsrv#248]
When will the next version be released，
I won t compile the program，
I'm a C # programmer，
now version1.1

**Comment by ruven** [comment]
Very soon! We're planning to do a full release at the end of the year or beginning of 2023.

**Comment by MichaelTran262** [comment]
Hello, is the new version already released?

**Comment by ruven** [comment]
I'm preparing the release right now in fact. It'll be ready this weekend!

**Comment by ruven** [comment]
Here it is: https://github.com/ruven/iipsrv/releases/tag/iipsrv-1.2
