### ISSUE TITLE
Compiling with Kakadu 8.3 

### ISSUE THREAD

**Issue by eduh** [ruven/iipsrv#258]
We try to compile iipimage with a trial license of kakadu 8.3 but we got stuck with this error:
2023-07-11T12:17:32.7666559Z [91mIn file included from KakaduImage.cc:29:
2023-07-11T12:17:32.7667832Z KakaduImage.h:37:10: fatal error: jpx.h: No such file or directory

Now the jpx.h is in this 8.3 trial at  ./apps/compressed_io/jpx.h
Is that location correct? 

Attached the log
[iipimage-kakadu83.txt](https://github.com/ruven/iipsrv/files/12014791/iipimage-kakadu83.txt)

**Comment by ruven** [comment]
I've committed a fix to the iipsrv configure script that prevents the error, so it should now compile. However, it doesn't detect your Kakadu installation. What exactly are you copying at step 5:

`Step 5/123 : COPY docker/kakadu83 /kakadu/ `

You need to compile Kakadu, but I see no mention of this in your log. Is this done separately and you just copy over the result?

**Comment by eduh** [comment]
Indeed I  compiled kakadu 8.3 seperately.  
After applying your fix it still did not found the kakadu 8.3 version.
It tries this location:
checking for /var/www/html/compiler/docker/kakadu-v8_3-02162E/managed/all_includes/jpx.h... no
configure: No Kakadu JPEG2000 Sources Found
So I just copied the contents of   kakadu-v8_3-02162E/apps/compressed_io/  to kakadu-v8_3-02162E/managed/all_includes and then the ./configure --with-kakadu=/var/www/html/compiler/docker/kakadu-v8_3-02162E  ended with success
Options Enabled:
---------------
 Memcached   :  false
 JPEG2000    :  true (Kakadu)
 OpenMP      :  true
 Loggers     :  file, syslog
 PNG Output  :  true
 WebP Output :  false

The  make command  however fails with this error
In file included from /var/www/html/compiler/docker/kakadu-v8_3-02162E/managed/all_includes/jpx.h:39,
                 from KakaduImage.h:37,
                 from FIF.cc:29:
/var/www/html/compiler/docker/kakadu-v8_3-02162E/managed/all_includes/jp2.h:49:10: fatal error: kdu_elementary.h: No such file or directory
   49 | #include "kdu_elementary.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

Now I can shuffle with directories again but that is not the way to go. I can send you the kakadu8.3  trial version (valid for 2 weeks) if you wish. Attached is also the filelisting of the 8.3 version.

[kakadu83-filelist.txt](https://github.com/ruven/iipsrv/files/12158845/kakadu83-filelist.txt)

**Comment by ruven** [comment]
Your Kakadu file listing indicates that it has not been compiled. After compilation you should have some .h files in managed/all_includes/ and some important .o files in app/make/. These are all missing and iipsrv cannot compile without these.

**Comment by eduh** [comment]
Working now.
I compiled kakadu with this makefile  as I did in version6
all:
	cd ../coresys/make; make -f $(KD_MAKEFILE) all
	cd ../apps/make; make -f $(KD_MAKEFILE) all_but_hyperdoc
	#cd ../managed/make; make -f $(KD_MAKEFILE) all

But it looks the last line in version 8.3 is now also needed. I recompiled kakadu and compiled the iipimage and it works now.
Thanks for the assistence. 
One question: if we switch to OpenJpeg and VIPS,  will it support the old kdu_compress generated tiles still?  As a test I compiled the iipsrv.fcgi without kakadu and it looks like it serves these tiles without any problem.

**Comment by ruven** [comment]
Kakadu provides an simpler way to compile. Just do:

`cd make; make -f $(KD_MAKEFILE) all_but_jni`

Yes, OpenJPEG should read all your Kakadu-encoded images without problems.
