### ISSUE TITLE
Degraded quality when scaling with '^!w,h' size

### ISSUE THREAD

**Issue by osandum** [ruven/iipsrv#273]
When size is specified with _`…/^!w,h/…`_ we see degraded output quality in comparison to the same image specified with explicit _`…/w,h/…`_.

E.g., a source image of 4,785×1,539 pixels, when rendered with `…/full/^!800,800/0/default.jpg` will return an 800×257 pixel JPEG, and thus we would expect the same image rendered with size explicitly set as `…/full/800,257/0/default.jpg` to return the same result. However, with the `iipsrv-1.2` build we see degraded output when using the _`…/^!w,h/…`_ format. See samples below.

`…/example.tif/full/^!800,800/0/default.jpg` (800×257px, 104Kb):
![autosize-800,800](https://github.com/user-attachments/assets/d4d36a07-0165-4a1f-9786-c3db8efcf832)

`…/example.tif/full/800,257/0/default.jpg`  (800×257px, 70Kb):
![explicit-800,257](https://github.com/user-attachments/assets/9da4478b-3e5c-4831-a315-6c2cd4d52751)

**Comment by ruven** [comment]
It looks like you found a very subtle bug. When you added the ! prefix to maintain aspect ratio, the wrong resolution level was getting selected forcing an overly large resize to be carried out. I've now fixed this in https://github.com/ruven/iipsrv/commit/7743d8230f4f6db2f72bb2d0997dd69eaa17aa7b, so you should now get good output quality in both cases.

**Comment by osandum** [comment]
Wow, that was quick. Thank you. I will test asap.
