### ISSUE TITLE
Vcxproj contains conflicted code

### ISSUE THREAD

**Issue by Niv1988** [ruven/iipsrv#28]
Seems that the vcxproj file contains a few unresolved conflicts which prevent it from being opened in visual Studio.

**Comment by tmtisfree** [comment]
Hi, I sent a working one to Ruven some time ago, which I use to build iipsrv.fcgi. Here the link to get it: http://tmtfree.hd.free.fr/uploads/iipsrv.vcxproj

**Comment by ruven** [comment]
Sorry, TPTisFree, I hadn't had time to look into your windows fixes, but I've now merged your project file. Thanks.
