### ISSUE TITLE
IIIF problem with retrieving info.json file for images in subdirectories?

### ISSUE THREAD

**Issue by higginsr** [ruven/iipsrv#32]
Hello
The IIIF image api requires encoding of subdirectory slashes in the base uri, which means a url like http://server/iipsrv?IIIF=/directory%2Fsubdirectory%2Fsubdirectory%2Ffile.jp2/full/full/0/default.jpg is needed.

However an info.json request for the same file will not work as http://server/iipsrv?IIIF=/directory%2Fsubdirectory%2Fsubdirectory%2Ffile.jp2/info.json, but only as http://server/iipsrv?IIIF=/directory/subdirectory/subdirectory/file.jp2/info.json. All you get with the %2F url is a truncated json file that stops at "directory".

Have I missed something in configuration? I've tried adjusting apache settings but it seems to be an iipsrv issue.
Thank you.

**Comment by ruven** [comment]
Sorry, that was an iipsrv bug. I've just uploaded a fix.
