### ISSUE TITLE
Segfault when FCGI parameters are not provided

### ISSUE THREAD

**Issue by brianhelba** [ruven/iipsrv#33]
When a request is made to IIP, and any of the FCGI parameters "QUERY_STRING", "SERVER_PROTOCOL", "HTTP_HOST", or "REQUEST_URI" are not set, IIP will segfault with no useful error message.

Two changes need to be made to fix this issue:
* Fix the code at ( https://github.com/ruven/iipsrv/blob/9ebed35f374f87a1a521a81ef327385fe0e08d93/src/Main.cc#L454 ) and ( https://github.com/ruven/iipsrv/blob/9ebed35f374f87a1a521a81ef327385fe0e08d93/src/Main.cc#L491 ). When a FCGI parameter is not present, "FCGX_GetParam" returns NULL. Attempting to assign NULL to a "std::string" causes a segfault.
* Improve the documentation for running IIP with Nginx ( http://iipimage.sourceforge.net/documentation/server/#nginx ) (and maybe some of the other servers, I haven't read through them all). The Nginx documentation does not mention that the lines:
```
        fastcgi_param   SERVER_PROTOCOL $server_protocol;
        fastcgi_param   REQUEST_URI $request_uri;
```
should also be present.

**Comment by ruven** [comment]
Thanks for this. I've updated the documentation on the website and in the README regarding NginX.

I've also uploaded a fix based on yours, which is slightly simpler and which keeps the const assignment to request_string and which avoids creating a separate http_if_modified_since string.

**Comment by brianhelba** [comment]
@ruven , thanks for the quick response to this. 
 
The reason I created a separate "http_if_modified_since" string variable is to avoid doing a map lookup twice. The performance cost of a string copy is much less than that of a map lookup. Further, if you saw my second commit, https://github.com/brianhelba/iipsrv/commit/2d7592b2f5b758422d843d5317fba0940472d05a , it's probably better to check whether the "HTTP_IF_MODIFIED_SINCE" parameter is empty, rather than just checking to see whether it exists at all, which is only possible by looking inside the string. Also, creating a string reference won't work, as it has the side effect of inserting "http_if_modified_since" into the map, which breaks later sections of code. 
 
Finally, while I'm happy to see IIP server being improved, I'd also like to be credited for the code that I write. If you need to modify a pull request, it would be nice if you added a patch of your own on top, instead of copy-pasting portions of else's code and committing it with you listed as the Git author. Alternatively, you can comment on the PR and give the author a chance to modify their own work. It's not a huge problem for a small patch like this, but I'd hope that if I submit larger fixes in the future, you will do the courtesy of ensuring that contributors are credited with Git authorship.

**Comment by ruven** [comment]
Sorry Brian, I did thank and reference you in the commit, but it's true it, in effect, stripped your git author tag. 

You're right about the side-effect of inserting an empty "http_if_modified_since" into the map. If you want to resubmit an update of your memcached patch, I'll be happy to merge that directly.
