### ISSUE TITLE
Missing files for make dist?

### ISSUE THREAD

**Issue by cmarmo** [ruven/iipsrv#36]
Hi Ruven,
trying a ```make dist``` in iipimage directory will complain some files are missing.
They are:
- ```PNGCompressor.h```
- ```PNGCompressor.cc```
- ```PTL.cc```

I'm not linking with PNG libraries, so no problem in compiling.
They have just been forgotten in some local repository? ;)

Cheers,
Chiara

**Comment by ruven** [comment]
OK, now fixed!
