### ISSUE TITLE
IIIF requests with a width arbitrarily larger than bounds of image return blurry images

### ISSUE THREAD

**Issue by magoni** [ruven/iipsrv#39]
**Expected behavior:** Regardless of whether an IIIF request has a width that is larger than the image bounds, the server should respond with a cropped image. (See http://iiif.io/api/image/2.0/#region : "If the request specifies a region which extends beyond the dimensions reported in the Image Information document, then the service should return an image cropped at the image’s edge, rather than adding empty space.")

**Actual behavior:** IIP responds with blurry images for IIIF requests exceeding a certain region width.

**Steps to reproduce:** Make a request to IIPImage using the IIIF syntax with a region width equal to or greater than 2x the width of the returned image for the same region at `full` size (greater than 4x the width at 50% size). Behavior occurs when size is specified as `pct:n`, `w,` , or `w,h`.

Example request (running IIP from current master branch):
Bad response:
http://dev-diva.simssa.ca/fcgi-bin/iipsrv.fcgi?IIIF=/srv/images/beromunster/bm_005.tif/2048,3072,884,1024/full/0/color.jpg

Good response:
http://dev-diva.simssa.ca/fcgi-bin/iipsrv.fcgi?IIIF=/srv/images/beromunster/bm_005.tif/2048,3072,883,1024/full/0/color.jpg

IIP log files for the responses:
https://gist.github.com/magoni/78733c94a1934a3a3895

Using the JTL syntax, edge tiles look fine: http://dev-diva.simssa.ca/fcgi-bin/iipsrv.fcgi?FIF=/srv/images/beromunster/bm_005.tif&JTL=2,11

**Comment by ruven** [comment]
It was a bit tricky to figure out what was going wrong here, but I've now updated a fix that should resolve this issue. Please test it out.
