### ISSUE TITLE
IIIF info.json not been generated properly if image filename contains spaces

### ISSUE THREAD

**Issue by adrianh-cogapp** [ruven/iipsrv#42]
Hi,

We are currently upgrading our IIPImage/OpenSeaDragon setup to be IIIIF compliant. 
We discovered during the process that the info.json is not been generated properly if the image name contains spaces.

Example:
http://XX.XX.XX.XX/iiif/images/81055/vdc_100000001524.0x000379/Mss%20Eur%20F126_1_0616.jp2/info.json

Returns:
```javascript
{
  "@context" : "http://iiif.io/api/image/2/context.json",
  "@id" : "http://XX.XX.XX.XX/iiif/images/81055/vdc_100000001524.0x000379/Mss       6.953200E-310ur
```
Note: the images are been served properly using:
http://XX.XX.XX.XX/iiif/images/81055/vdc_100000001524.0x000379/Mss%20Eur%20F126_1_0616.jp2/full/,1200/0/default.jpg

Please let me know if you need more information.

**Comment by ruven** [comment]
Are you using the latest iipsrv source code? I don't get this problem if I try myself.

**Comment by adrianh-cogapp** [comment]
I wasn't. I've just tested with the latest commit and it now seems to be working fine.
Thanks
