### ISSUE TITLE
URL is getting decoded twice

### ISSUE THREAD

**Issue by clu-pei-dae** [ruven/iipsrv#44]
We're having filenames that contain special characters like the +-sign. Therefore, we escape the + as %2B which works perfectly fine when opening the image with the following URL:

/fcgi-bin/iipsrv.fcgi?FIF=imageStorage/nb_vol001_issue0001_0156%2B0157.tif&cnt=1&sds=0,90&jtl=4,1

However, when I try to open the following URL, I get an "neither a file nor part of an image sequence"-Error:
/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/nb_vol001_issue0001_0156%2B0157.tif/full/512,512/0/default.jpg

 When opening the log, it says the following:

Full Request is IIIF=imageStorage/nb_vol001_issue0001_0156%2B0157.tif/full/512,512/0/default.jpg
[1/1]: Command / Argument is IIIF : imageStorage/nb_vol001_issue0001_0156%2B0157.tif/full/512,512/0/default.jpg
IIIF handler reached
FIF handler reached
FIF :: Image cache miss
/media/imageStorage/nb_vol001_issue0001_0156 0157.tif is neither a file nor part of an image sequence
Sending HTTP 404 Not Found
Total Request Time: 305 microseconds
image closed and deleted

I guess the problem is, that the URL is parsed twice. The first time it is parsed to the correct filename (/media/imageStorage/nb_vol001_issue0001_0156+0157.tif) and then the + sign get's parsed as HTTP-URL again and therefore becomes a space (/media/imageStorage/nb_vol001_issue0001_0156 0157.tif).

Is there a bugfix or some way to fix this?

Thank's for your help!

**Comment by nicolasfranck** [comment]
I think the double decoding is correct. 

The IIIF specification expects you to url-encode the identifier.
All other parameters are put as path segments.

BUT when you send it to iipsrv , you must url-encode the WHOLE
IIIF part. So the identifier is url-encoded twice:

/iiif/%2Fdata%2Fmyfile.tif/full/full/0/default.jpg

becomes:

/iipsrv.fcgi?IIIF=%252Fdata%252Fmyfile.tif%2Ffull%2Ffull%2F0%2Fdefault.jpg

**Comment by ruven** [comment]
So, the current "double decoding" implementation in iipsrv is in fact correct? Does anyone else have any other views or comments on this issue?
