### ISSUE TITLE
glibc 2.14 required?

### ISSUE THREAD

**Issue by nicolasfranck** [ruven/iipsrv#51]
Compiling iipsrv fails on Centos 6:

```
[..]
libtool: link: g++ -std=gnu++0x -g -O2 -o iipsrv.fcgi IIPImage.o TPTImage.o JPEGCompressor.o TileManager.o IIPResponse.o View.o Transforms.o Task.o OBJ.o FIF.o JTL.o TIL.o ICC.o CVT.o Zoomify.o DeepZoom.o SPECTRA.o PFL.o IIIF.o Watermark.o Main.o KakaduImage.o -fopenmp /home/install/ugent-kakadu/v6_4_1-01131N/apps/make/jpx.o /home/install/ugent-kakadu/v6_4_1-01131N/apps/make/jp2.o /home/install/ugent-kakadu/v6_4_1-01131N/apps/make/kdu_stripe_decompressor.o  -L/home/install/ugent-kakadu/v6_4_1-01131N/apps/make -lkdu_v64R -lpthread ../fcgi/libfcgi/libfcgi.a -ljpeg -ltiff -lm
/home/install/ugent-kakadu/v6_4_1-01131N/apps/make/libkdu_v64R.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: ld returned 1 exit status
make[1]: *** [iipsrv.fcgi] Error 1
make[1]: Leaving directory `/home/install/iipsrv/src'
make: *** [all-recursive] Error 1
```

It complains that glibc 2.14 is required. Is this version really required, or can it be done with lower versions? Glibc 2.12 is standard on all Centos 6, and higher versions I do not find for this OS.

Compiling the libraries and binaries of kakadu themselves do not give this error, although
libkdu_v64R.so is also used there.

**Comment by ruven** [comment]
No, iipsrv does not require any specific version of libc and will work with old versions. Your error, however, refers not to iipsrv, but to your Kakadu library, which seems to have been built against glibc 2.14. Perhaps you should do a full recompile of this first.

**Comment by nicolasfranck** [comment]
You're right, my fault. I was copying between systems, and forgot to clean the built code.
