### ISSUE TITLE
IIIF: server hangs when width or height are zero

### ISSUE THREAD

**Issue by nicolasfranck** [ruven/iipsrv#52]
When I set the width or height of a region to "0", then the iipsrv hangs forever

version of iipsrv: 1.0 (git branch)

The last I see in the log:

```
Full Request is IIIF=/data/datadir/2012/1/27/10/40/5/1139-P-00001_2004_0001_AC.jp2/0,0,0,100/full/0/default.jpg
[1/1]: Command / Argument is IIIF : /data/datadir/2012/1/27/10/40/5/1139-P-00001_2004_0001_AC.jp2/0,0,0,100/full/0/default.jpg
IIIF handler reached
IIIF :: URL decoded to /data/datadir/2012/1/27/10/40/5/1139-P-00001_2004_0001_AC.jp2/0,0,0,100/full/0/default.jpg
FIF handler reached
FIF :: URL decoding/filtering: /data/datadir/2012/1/27/10/40/5/1139-P-00001_2004_0001_AC.jp2 => /data/datadir/2012/1/27/10/40/5/1139-P-00001_2004_0001_AC.jp2
FIF :: Image cache initialization
FIF :: JPEG2000 image detected
FIF :: Created image
FIF :: Image dimensions are 2008 x 3009
FIF :: Image contains 3 channels with 8 bits per channel
FIF :: Image timestamp: Wed, 07 Oct 2015 14:35:42 GMT
FIF :: Total command time 1137 microseconds
IIIF :: Requested Region: x:0, y:0, w:0, h:100
IIIF :: Requested Size: 8x100
IIIF :: Requested Rotation: 0 degrees
IIIF :: Requested Quality: default with format: jpg
IIIF :: image request for /data/datadir/2012/1/27/10/40/5/1139-P-00001_2004_0001_AC.jp2 with arguments: region: 0,0,8,100; size: 8x100; rotation: 0; mirroring: 0
```

**Comment by ruven** [comment]
There was an infinite loop due to the zero region size. I just uploaded a fix for this. Please try it out

**Comment by nicolasfranck** [comment]
ok, this works. Thanks.

But why do you force the output to an one-pixel-image if the width or height is invalid?
Wouldn't it be more accurate to respond with an error message like you do when the iiif "size"
is invalid?

**Comment by ruven** [comment]
I've set the minimum size to 1px, so the requested zero-sized image is rounded up to this minimum size. I've tried to make iipsrv tolerant of parameter syntax errors for other protocols and not send too many errors, but perhaps for IIIF requests, you're right, it would make sense to send an error in this case.

**Comment by ruven** [comment]
I just added a check so that it now throws an error in this case
