### ISSUE TITLE
Error 25:3

### ISSUE THREAD

**Issue by Mtillmann** [ruven/iipsrv#54]
Hi I am trying to get iipsrv running with leaflet. The server is answering regular requests without a problem but it seems that the retrieval of certain metadata fails. I could not find any documentation of the metadata service so I am asking here what could be the cause of such an error:

Request
```
.../fcgi-bin/iipsrv.fcgi?FIF=o.tif&obj=IIP,1.0&obj=max-size&obj=tile-size&obj=resolution-number&obj=bits-per-channel&obj=min-max-sample-values&obj=subject
```
Response
````
Error/25:3 2 min-max-sample-val
````

I am using iipsrv/0.9.9 from the ubuntu repo. The image i am using is a 16k JPEG converted to TIFF using the imagemagick method described in the docs. Any pointers in the right direction would be great!

**Comment by Mtillmann** [comment]
I compiled from source, the error has vanished

**Comment by ruven** [comment]
Indeed the Leaflet plugin currently requires the latest development/1.0 version of iipsrv

**Comment by Mtillmann** [comment]
Thanks, i should have visited leaflet.tilelayer.iip's issues page!
