### ISSUE TITLE
support level 0 attribute "sizes" in info.json?

### ISSUE THREAD

**Issue by nicolasfranck** [ruven/iipsrv#59]
Since some resolutions are present in the jpeg2000 file or pyramid tiff,
one could add the attribute sizes in the info.json

cf. http://iiif.io/api/image/2.0/#image-information

That would make the server usable for level-0-clients.

**Comment by ruven** [comment]
OK, I just made a commit adding this. Please test it out.

**Comment by nicolasfranck** [comment]
ok thanks, I'll test it

**Comment by nicolasfranck** [comment]
Seems to work, although I have not found a level 0 client yet ;-)
I also think you need the add the feature "sizeByWhListed" to the list of "supports"

**Comment by nicolasfranck** [comment]
I see that the draft of the image api 2.1 specifies the attribute **maxWidth**.
Would be nice for the next version, if it's the official api then.

**sizes** is now confined  by MAX_CVT in your code, but clients
do not interpret **sizes** as a request limit. Therefore, when they ask for
the **full* view, they get the wrong resolution  (limited by MAX_CVT!) they
asked for (e.g. 5000x5000 instead of 10000x10000).

**Comment by ruven** [comment]
But isn't sizes supposed to be a list of recommended _available_ sizes? The spec says this:

> A set of height and width pairs the client should use in the size parameter to request complete images at different sizes that the server has available. This may be used to let a client know the sizes that are available when the server does not support requests for arbitrary sizes, or simply as a hint that requesting an image of this size may result in a faster response

The width and height attribute will give you the full native size of the image and the sizes attribute should give you the sizes available (and therefore limited by MAX_CVT) from the server.

**Comment by ruven** [comment]
>  I also think you need the add the feature "sizeByWhListed" to the list of "supports"

This is a required feature for both level 0 and level1 compliance (http://iiif.io/api/image/2.0/compliance/) and, therefore, is (should be) already included in the profile http://iiif.io/api/image/2/level1.json

**Comment by nicolasfranck** [comment]
About the sizes: sizes report the resolutions that can be retrieved in a fast way, OR the only resolutions it has when, when it does not allow for arbitrary sizes (level 0?).

It does not state that other resolutions cannot or may not be requested.
That's why they introduced **maxWidth** in  the draft version of the Image API (2.1).

**Comment by ruven** [comment]
The spec talks about _available_ sizes, which to me means the sizes that the server is ready and able to deliver. Yes, I could simply send a list of all the _existing_ resolutions, but the specs for both 2.0 and 2.1 say this about the sizes parameter:

> A request constructed with the w,h syntax using these sizes must be supported by the server

IIPImage will not give you anything larger than the MAX_CVT value, so it would be incorrect to include such sizes.

**Comment by nicolasfranck** [comment]
You're right. But that's what I meant ;-)

I'm just wondered about why viewers like Mirador and UniversalViewer do not interpret these sizes
as a limit, but simply think there going to get the full image when requesting for full size.

But I think it's better to ask the creator of UniversalViewer ;-), and the implementors of IIIF.
Thanks!

If you want more info:

e.g. info.json (I added the **maxWidth** myself, but it had no influence for the moment)
```
http://shared.ugent.be/IIIF/images/archive.ugent.be%3A125B75B2-D858-11E2-9632-BBFE97481370%3ADS.1/info.json
```
used here:
```
http://shared.ugent.be/viewer/archive.ugent.be%3A125B75B2-D858-11E2-9632-BBFE97481370
```
Below on the left, there a download icon. Click, and look at the second option where it states:
```
 4759 x 6928px
```
It uses the width and height of the full image to display, but once you download it, you see that
it does not have that size.

That's why I thought: why do they introduce **maxWidth**, if the maximum size of sizes is in fact the limit?

**Comment by ruven** [comment]
> That's why I thought: why do they introduce maxWidth, if the maximum size of sizes is in fact the limit?

Remember that _sizes_ can also simply be a "... hint that requesting an image of this size may result in a faster response". So, _sizes_ doesn't necessarily give you the absolute maximum available size, especially if the server allows arbitrary sizes. So, in many cases _maxWidth_ will be higher than the largest value given by _sizes_.

**Comment by nicolasfranck** [comment]
So, the conclusion is: if there is a MAX_CVT, and it's lower than the actual width, there should be a maxWidth property to inform clients that requesting any width beyond that limit is futile? The clients do not support this yet, I know.

**Comment by ruven** [comment]
> So, the conclusion is: if there is a MAX_CVT, and it's lower than the actual width, there should be a maxWidth property to inform clients that requesting any width beyond that limit is futile?

Yes, that's my understanding of the wording of the spec and it makes sense to do it this way through a separate _maxWidth_ value. As you say, it'll need clients to be updated to handle this correctly.
