### ISSUE TITLE
Add JSON response for getting server info

### ISSUE THREAD

**Issue by ahankinson** [ruven/iipsrv#6]
It would be nice if we could query the iipsrv.fcgi instance and return a JSON formatted list of features this instance supports. For example:

```
http://example.com/fcgi-bin/iipsrv.fcgi?getInfo
```

Might return:

```
{
"name": "IIP Image Server",
"version": "1.0.0",
"enabled_modules": ["TIFF", "Kakadu"]
... Any other data ...
}
```

**Comment by ahankinson** [comment]
Since IIP now serves out IIIF, I think this has mostly been addressed.

**Comment by ruven** [comment]
There are, in fact, IIP protocol requests available to obtain a list of supported features. OBJ=iip-opt-comm and OBJ=iip-opt-obj will return respectively the list of available commands and possible metadata available. Though, something in JSON (or XML) would indeed make more sense today. Perhaps also a request to get all the image metadata from a TIFF or JPEG2000 including comment fields could be useful.

**Comment by ahankinson** [comment]
Actually, thinking back on this I think I actually meant info about the FCGI itself: The version of IIP, whether it supported JPEG2000, etc. Right now visiting just the FCGI shows you an HTML page, but being able to query it for information in JSON might be useful.
