### ISSUE TITLE
IIIF protocol: wrong aspect ratio

### ISSUE THREAD

**Issue by dsecik** [ruven/iipsrv#60]
Hi,
this problem was discussed in #21. It seems that it still occurs if the width or height of requested region is very small. For example ```1024,1024,2,512/2,/0/default.jpg``` outputs 2x128 image instead of 2x512.

**Comment by ruven** [comment]
Your example request gives me a 2x512px image using the latest source code. Try again using an updated build. If it still doesn't work, what is the native size of your image?

**Comment by dsecik** [comment]
I created new build from source and it's working fine. (My previous build was aprox. 4 months old) Thanks for help.
