### ISSUE TITLE
Problem: --with-kakadu parameter and lib placement

### ISSUE THREAD

**Issue by fractos** [ruven/iipsrv#67]
I've tried using ./configure --with-kakadu=/opt/kakadu/kakadu-7.5 but this leaves the bare lib name of "libkdu_v75R.so" in the FCGI executable, instead of what I was expecting "/opt/kakadu/kakadu-7.5/apps/make/libkdu_v75R.so". This is causing an installation of iipsrv with lighttpd and Kakadu-support to fail if following the instructions.

I see that configure.ac was changed by commit [https://github.com/ruven/iipsrv/commit/880cfd14ea00b2e133f01310c47093ffcefcfb13]

Although I can understand the reason for the change, it's not mentioned in the Git instructions that you have to have the Kakadu library in the same folder as the executable now.

**Comment by ruven** [comment]
It doesn't have to be in the same folder, but only somewhere in the LD_LIBRARY_PATH. The commit removed the hard-wired path, making installation more flexible about where you put the libdku library.

In your case, the easiest solution is simply to add /opt/kakadu/kakadu-7.5/apps/make/ to the LD_LIBRARY_PATH for the lighttpd process.

**Comment by fractos** [comment]
After thinking about it some more, this will directly affect how we have the combination of iipsrv and lighttpd deployed in production, in a configuration that uses Kakadu. This will require changes to existing docker container instructions. I hear what you're saying about LD_LIBRARY_PATH, but even that has various knock-on effects with active production environments.
