### ISSUE TITLE
[IIIF] "gray" is not a recognized feature for supports

### ISSUE THREAD

**Issue by azaroth42** [ruven/iipsrv#72]
Per: http://merovingio.c2rmf.cnrs.fr/iiif/HD7.tif/info.json

That the server supports the `gray` quality is indicated already in the qualities list.  Features in the supports list that aren't defined by the specification, must be URIs.

(minor, and noting that `native` in the qualities field does _not_ have the same issue)

**Comment by ruven** [comment]
So, what you are saying is that gray should simply be removed from the supports list. Correct?

**Comment by azaroth42** [comment]
Thanks Ruven!
