### ISSUE TITLE
JPEG 2000 support broken in HEAD

### ISSUE THREAD

**Issue by ahankinson** [ruven/iipsrv#73]
Commit a0849aa01de56e69d684766e0c7c9fc840a29762 is producing a bad build for us on Ubuntu 14.04.4 machines (not tested on anything else). 

The latest (HEAD) compiles, but when it tries to display a JPEG 2000 image it produces the error:

```
Error in `/usr/local/share/iipsrv-latest/iipsrv/src/iipsrv.fcgi': munmap_chunk(): invalid pointer: 0x0000000001c8eca0 
Error in `/usr/local/share/iipsrv-latest/iipsrv/src/iipsrv.fcgi': munmap_chunk(): invalid pointer: 0x0000000001083ca0 
Error in `/usr/local/share/iipsrv-latest/iipsrv/src/iipsrv.fcgi': munmap_chunk(): invalid pointer: 0x000000000254bca0 
Error in `/usr/local/share/iipsrv-latest/iipsrv/src/iipsrv.fcgi': double free or corruption (out): 0x0000000002082ca0 
Error in `/usr/local/share/iipsrv-latest/iipsrv/src/iipsrv.fcgi': free(): invalid size: 0x0000000001afdca0 
```

This occurs with both KDU 7.7.1 and 7.8. 

Reverting this change:
https://github.com/ruven/iipsrv/commit/a0849aa01de56e69d684766e0c7c9fc840a29762#diff-4b5b06b344106556a47cef8e50e19e92L584

seems to fix it.

Thanks to @jeromepl for finding this one.

**Comment by ahankinson** [comment]
Following up: has anyone else encountered this? It's a pretty big problem for us, but outside confirmation would be useful.

**Comment by ruven** [comment]
OK, I think I see where this has come from - I've just submitted a fix. Please try it out and tell me if it works for you.

**Comment by ahankinson** [comment]
Great, thanks Ruven. We'll check it out.

**Comment by jeromepl** [comment]
Seems to work perfectly now!
