### ISSUE TITLE
Error when fetching info for some images

### ISSUE THREAD

**Issue by amitev** [ruven/iipsrv#76]
Hello, I have installation very similar to this provided by the [docker image](https://github.com/bodleian/iipsrv-openjpeg-docker) but my I build directly from the master branch of this repo (not from the fork of stweil). When compiling I provide the --enable-openjpeg option to the ./configure command and have openjpeg installed. However when I request info.json for some images (i.e. url http://..../fcgi-bin/iipsrv.fcgi?IIIF=63aa6713-d643-4b6a-9c6a-fc0dae0bd069.ptif/info.json) I get an exception. The apache responds with code 500 saying that:

> [fcgid:warn] [pid 27:tid 139732331788032] [client 172.17.0.1:38043] mod_fcgid: error reading data, FastCGI server closed connection
> [core:error] [pid 27:tid 139732331788032] [client 172.17.0.1:38043] End of script output before headers: iipsrv.fcgi
> [fcgid:error] [pid 26:tid 139732498884480] mod_fcgid: process /var/www/localhost/fcgi-bin/iipsrv.fcgi(104) exit(communication error), get unexpected signal 11

However if I request the image with specific dimensions (i..e http://..../fcgi-bin/iipsrv.fcgi?IIIF=63aa6713-d643-4b6a-9c6a-fc0dae0bd069.ptif/full/,64/0/default.jpg) the iip server provides the image correctly.

I'm attaching [an archive](https://github.com/ruven/iipsrv/files/393600/iip-server.zip) holding the particular image and the iip server log file (iipsrv.log).

**Comment by ruven** [comment]
OK, I've just submitted a fix to this. It was being caused by the info.json code not properly accounting for images with only 1 resolution level.
