### ISSUE TITLE
unchecked pkg-config dependency

### ISSUE THREAD

**Issue by opqrs** [ruven/iipsrv#78]
configure.ac uses pkg-config to check for openjpeg, but autogen.sh does not check for pkg-config, resulting in a broken configure script:
```
./configure: line 18075: syntax error near unexpected token `OPENJPEG,'
./configure: line 18075: `		    PKG_CHECK_MODULES(OPENJPEG, libopenjp2, OPENJPEG=true, OPENJPEG=false)'
```

**Comment by ruven** [comment]
The autogen.sh script is a generic one, so I added a check for pkg-config to configure.ac. This is not an ideal solution, but it at least avoids a broken configure script.
