### ISSUE TITLE
MAX_SIZE breaks aspect ratio

### ISSUE THREAD

**Issue by nicolasfranck** [ruven/iipsrv#81]
If the request width is higher than the configured MAX_SIZE, it is set to MAX_SIZE.
If the request height is higher than the configured MAX_SIZE, it is set to MAX_SIZE.

So if both are higher, they are both set MAX_SIZE.

Either way, this breaks the aspect ratio of the image.

Shouldn't the highest value (width or height) be set to MAX_SIZE, and the other one
recalculated, instead of resetting them independently?

**Comment by nicolasfranck** [comment]
ok, I realize that in the current spec 2.0 the feature sizeByForcedWh can lead to distorted
images.

In spec 2.1. there is a joice: either support sizeByWh or sizeByDistortedWh. Both share the same syntax (w,h), but have a different behaviour:

* sizeByWh only returns an image if it does not break the aspect ratio
* sizeByDistortedWh always breaks the aspect ratio (the sizeByForcedWh from 2.0)

cf. http://iiif.io/api/image/2.1/#profile-description

Wouldn't it be better just to throw an error ("invalid request") rather than trying to fix the image bounds?

**Comment by ruven** [comment]
OK, I've now committed a fix for this and the aspect ratio is now respected in this case. Please test it out.
