### ISSUE TITLE
add capabilities to info.json

### ISSUE THREAD

**Issue by nicolasfranck** [ruven/iipsrv#82]
The iipsrv is able to do more than the info.json say. Wouldn't it be better to
add these feature names:

SUPPORTS:
* regionByPx
* sizeByW
* sizeByH

QUALITIES:
* default

"native" is not listed anymore in spec 2.0 and later. Maybe leave it there for the moment, or remove it?

**Comment by nicolasfranck** [comment]
See https://github.com/ruven/iipsrv/pull/83

**Comment by ruven** [comment]
_sizeByW_, _sizeByH_ and _regionByPx_ are all already included within the [level 1 profile](http://iiif.io/api/image/2.0/compliance/#size) for both IIIF 2.0 and 2.1, so it shouldn't be necessary to include them as a _supports_ feature.

For IIIF 2.1 and later, we'll have to see how to best handle changes. Are IIIF servers supposed to be backwards compatible? Or would it be better to simply remove deprecated features and declare iipsrv as an IIIF 2.1 server.
