### ISSUE TITLE
Setting compression level on-the-fly with IIIF?

### ISSUE THREAD

**Issue by waltsatan** [ruven/iipsrv#84]
When using the IIIF protocol, is it possible to set JPEG_QUALITY?  It's not officially in the IIIF API spec (it's been discussed), but since IIPImage supports it in IIP mode, maybe there's a way to do this unofficially?

**Comment by ruven** [comment]
You are correct that this is not part of the IIIF API and there's currently no unofficial way to do this. However, if a fixed value for all IIIF requests is all you need, you can set this server-side through the JPEG_QUALITY parameter, which will set the default quality level.

If you want to set per-request qualities, you should simply do it as an IIP request. Remember that it's possible to use both IIP and IIIF API with the same IIPImage server.

**Comment by waltsatan** [comment]
I was previously using IIP, but now have a requirement needing IIIF's !w,h sizing to fit an image in a specified area.  I guess I'm stuck in a feature conundrum, unless there's some unofficial way to fit-to-box in an IIP request? (without first querying image size)

**Comment by ruven** [comment]
You should be able to do the same thing in an IIP request by setting both WID and HEI simultaneously. For example ,`WID=500&HEI=500&CVT=JPEG` will fit the image into a 500x500 px box.

**Comment by waltsatan** [comment]
Ahh, jeez!  When I was testing, I had put the HEI after CVT and it was ignoring it.  Thanks for the help.
