### ISSUE TITLE
Region: square support?

### ISSUE THREAD

**Issue by waltsatan** [ruven/iipsrv#85]
Any timetable for support of IIIF API 2.1's "square" region?

http://iiif.io/api/image/2.1/#region

**Comment by waltsatan** [comment]
I added this to IIIF.cc:263 if anyone needs it:

```
	  // Square region export request
	  else if (regionString == "square" ) {
	  	if ( height > width ) {
	  		float hi = (float)width/(float)height;
	  		session->view->setViewTop( (1-hi)/2.0 );
			session->view->setViewHeight( hi );
		} else if ( width > height ) {
			float wi = (float)height/(float)width;
	  		session->view->setViewLeft( (1-wi)/2.0 );
			session->view->setViewWidth( wi );
		} else {
			//do nothing - square already
		}
	  }
```

**Comment by ruven** [comment]
Thanks, I've just added this functionality based on your suggestion and patch.

**Comment by waltsatan** [comment]
My project required a custom cropping region - instead of a square, I needed a rectangle.  I added this ability through a "ratio:" region selector.

For example, `[filename].tif/ratio:0.5/,500/0/default.jpg` will always return a 250x500px image (You can set size with either w, h, or both).

I know this is totally out of IIIF spec (it would be a nice addition, though), but it's a useful feature for anyone looking for similar functionality:

```
	else if (regionString.substr(0, 6) == "ratio:" ){
		float ratio;
		istringstream i( regionString.substr( regionString.find_first_of(":") + 1, string::npos ) );
        	if ( !(i >> ratio) ) throw invalid_argument( "invalid ratio" );

		float h = ((float)width/(float)height)*(1/ratio);

		if ( height > width && h <= ratio ){
			session->view->setViewTop( (1-h)/2.0 ); 
			session->view->setViewHeight( h );
		}
		else {
			float w = ((float)height/(float)width)*ratio;

			session->view->setViewLeft( (1-w)/2.0 );
			session->view->setViewWidth( w );
        	}
	} 
```
