### ISSUE TITLE
IIIF invalid jpegs in grey quality

### ISSUE THREAD

**Issue by dsecik** [ruven/iipsrv#87]
IIPImage built from the latest code on github returns invalid jpegs for some regions and sizes if the quality is grey (works fine for default) . I was able to reproduce this on all images I tried with the following request. 

`{scheme}://{server}{/prefix}/{identifier}/0,0,1024,1024/256,/0/gray.jpg`

Older build of version 1.0 returns correct images so we rolled back for now.

**Comment by ruven** [comment]
This should now be fixed in the latest code
