### ISSUE TITLE
Request for a corrupt image file causes IIP server process to stop responding.

### ISSUE THREAD

**Issue by neilh-cogapp** [ruven/iipsrv#88]
We've discovered that a broken or corrupt jp2 image file can cause the iipsrv process to crash and become unrecoverable. Restarting the Apache web server process manually gets it working again for other images.

Last log output is `FIF :: JPEG2000 image detected` so it seems to happen around the point at which IIP invokes `new KakaduImage()`. I have attached the image file.

Recreated on a test environment running:
- IIP v1.0
- Kakadu v7_4-01474C
- Apache 2.4
- fastcgi 

**Log output during request for the bad image from IIP log level 10**
```
Full Request is iiif=IOR_R_15_1_514_0249-bad.jp2/full/!1200,/0/default.jpg
[1/1]: Command / Argument is iiif : IOR_R_15_1_514_0249-bad.jp2/full/!1200,/0/default.jpg
IIIF handler reached
IIIF :: URL decoded to IOR_R_15_1_514_0249-bad.jp2/full/!1200,/0/default.jpg
FIF handler reached
FIF :: URL decoding/filtering: IOR_R_15_1_514_0249-bad.jp2 => IOR_R_15_1_514_0249-bad.jp2
FIF :: Image cache initialization
FIF :: JPEG2000 image detected
<----------------------------------->
Wed Feb  8 14:34:27 2017

IIPImage Server. Version 1.0
*** Ruven Pillay <ruven@users.sourceforge.net> ***

Verbosity level set to 10
Running in FCGI mode

Setting maximum image cache size to 128MB
Setting filesystem prefix to ''
Setting default JPEG quality to 90
Setting maximum CVT size to 5000
Setting 3D file sequence name pattern to '_pyr_'
Setting up JPEG2000 support via Kakadu SDK


Initialisation Complete.
<----------------------------------->
```

**Log output from Apache logs level trace8**
```
[Wed Feb 08 16:48:19.820693 2017] [fastcgi:error] [pid 4541:tid 140021654853376] [client :47423] FastCGI: incomplete headers (0 bytes) received from server "/usr/lib/cgi-bin/iipsrv.fcgi"

terminate called after throwing an instance of 'int'
[Wed Feb 08 16:48:19.820717 2017] [:warn] [pid 4539:tid 140021907412864] FastCGI: server "/usr/lib/cgi-bin/iipsrv.fcgi" (pid 4559) terminated due to uncaught signal '6' ((null)), a core file may have been generated
[Wed Feb 08 16:48:19.820999 2017] [:warn] [pid 4539:tid 140021907412864] FastCGI: server "/usr/lib/cgi-bin/iipsrv.fcgi" restarted (pid 4643)
```

**Comment by neilh-cogapp** [comment]
[IOR_R_15_1_514_0249-bad.jp2.zip](https://github.com/ruven/iipsrv/files/761392/IOR_R_15_1_514_0249-bad.jp2.zip)

**Comment by neilh-cogapp** [comment]
[bad.jp2.zip](https://github.com/ruven/iipsrv/files/761395/bad.jp2.zip)

**Comment by ruven** [comment]
OK thanks, I've had a look and found the problem. Your images are missing a JP2 codestream, so I've added some extra error handling to prevent iipsrv from crashing in these situations. The latest github code should now run without problems with these images.
