### ISSUE TITLE
Support injection of ICC Color Profiles from Source images into JPEG tiles

### ISSUE THREAD

**Issue by beaudet** [ruven/iipsrv#91]
If a PTIF or JP2 source image has an embedded color profile and no color-related operations are included in the request, support retention of an embedded ICC color profile in the source image.  This should default to being disabled for backwards compatibility.

**Comment by ruven** [comment]
Yes, absolutely, the profile should simply be copied over to the iipsrv output image.

**Comment by beaudet** [comment]
@ruven can you please create a branch for ICC color profiles?

**Comment by beaudet** [comment]
I'll go ahead and submit this against master for now, but I can easily submit against an icc branch if / when that's ready.

**Comment by ruven** [comment]
I've just merged code to embed ICC profiles into master. I based it on your implementation, but simplified things and re-factored various things in JPEGCompressor to make embedding this (and XMP) data easier. ICC profile embedding is **enabled** by default, which I think is the behaviour most people would expect.

Thanks for your help with this and please test it out.

**Comment by beaudet** [comment]
Awesome sauce. Hopefully late next week.
