### ISSUE TITLE
Support IIIF URLs natively without requiring a rewrite or proxy configuration

### ISSUE THREAD

**Issue by beaudet** [ruven/iipsrv#93]
Apparently mod_rewrite with the proxy option [P] apparently does not use connection pooling and therefore will result in a large number of sockets being open for a heavily used IIP server.  So, it seems that mod_proxy would be preferable as far as resource consumption is concerned although mod_proxy doesn't support query strings and, in fact, it escapes the ? in a query string to %3F when handling a configuration like this:

ProxyPassMatch      ^/iiif/(.*)$   http://127.0.0.1/fastcgi/iipsrv.fcgi?IIIF=/$1

So.... without requiring admins to getting into the weeds of an even deeper Apache configuration to unescape the %3F before mod_proxy handles it, it would seem a lot more natural for IIP to just handle IIIF URLs natively.  Thus this enhancement request. 

So, I'd like IIP to be able to be configured with a new configuration option "IIIF_PREFIX" which, if detected in the REQUEST_URI will be removed from REQUEST_URI and a query string automatically created by just appending the redacted REQUEST_URI to "IIIF=".  This change, in conjunction with a single new ScriptAlias configuration, can enable native handling of IIIF URLs by IIP Server.

e.g.
ScriptAlias /iiif /var/www/fastcgi/iipsrv.fcgi

For those who wish to use mod_proxy, it might also make sense to create a configuration that enables detection of %3F in the absence of a QUERY_STRING and to unescape %3F and just handle it as a request with a query string after that.  Some performance testing to discover whether in fact mod_rewrite is actually more resource intensive than mod_proxy would be warranted before starting this portion of the activity though and I will create a different enhancement request for this aspect.

**Comment by ruven** [comment]
I just added a more generic version of this functionality in this commit: [be1c827cff8d885a718f1807d5a4a3d5b73cfb90](https://github.com/ruven/iipsrv/commit/be1c827cff8d885a718f1807d5a4a3d5b73cfb90)

There is now a new environment variable called URI_MAP which allows you to specify a prefix (which can even be empty) and one of iipsrv's supported protocols (IIP,IIIF,DeepZoom or Zoomify). These should take the form: "prefix=>protocol".

So, in your example, to enable requests to /iiif/ to be natively redirected by iipsrv to the IIIF handler, set URI_MAP to "iiif=>IIIF". No more URL rewriting required!

**Comment by beaudet** [comment]
excellent

**Comment by beaudet** [comment]
Ruven, it seems the IIIF viewer Universal Viewer tacks on query parameters in its URLs, probably to thwart caching.  Unfortunately, IIP is interpreting this additional query parameter as an unrecognized command and returning a 400 response rather than an image.  If you haven't modified IIP to disable processing of query strings when a url prefix matches, that should probably be done as well to avoid breaking existing IIIF viewers.

**Comment by ruven** [comment]
I'd have to reverse the logic. At the moment, if there's no query string, it checks for a url prefix match. To avoid your problem, it would need to first check for a url prefix match before checking for the existence of a query string.

**Comment by beaudet** [comment]
Yes, the prefix would have to be checked for a match each time.  I think that's probably ok though, right?

**Comment by ruven** [comment]
OK, I've just modified the implementation to do that: [commit: 660056f](https://github.com/ruven/iipsrv/commit/660056fbe234a45e3494ab1cc9c972a799c4689a)
