### ISSUE TITLE
Consider whether to support mod_proxy by unescaping %3F in certain situations

### ISSUE THREAD

**Issue by beaudet** [ruven/iipsrv#94]
Apparently mod_rewrite with the proxy option [P] apparently does not use connection pooling and therefore might result in a large number of additional sockets being open for a heavily used IIP server under a configuration like this:

RewriteRule         ^/iiif/(.*)$    /fastcgi/iipsrv.fcgi?IIIF=/$1 [P,NC]

So, it seems that mod_proxy would be preferable as far as resource consumption is concerned although mod_proxy doesn't support query strings and, in fact, it escapes the ? in a query string to %3F when handling a configuration like this:

ProxyPassMatch      ^/iiif/(.*)$   http://127.0.0.1/fastcgi/iipsrv.fcgi.?IIIF=/$1

It might also make sense to create an IIP configuration that enables detection of %3F in the absence of a QUERY_STRING and to unescape %3F and just handle it as a request with a normal query string. 

However, some performance testing to discover whether in fact mod_rewrite is actually more resource intensive than mod_proxy would be warranted before proceeding.

**Comment by ruven** [comment]
This is only an issue if you require URL rewriting. The latest commits related to #93 should avoid this kind of escaped character problem.

**Comment by beaudet** [comment]
yup
